// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2006 Mathématiques Appliquées SA (MASA)
//
// *****************************************************************************

#include "adaptation_app_pch.h"

// *****************************************************************************
// physical.xml
// *****************************************************************************
static const char* physicalXml =
"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>"
"<physical>"
"  <decisional file=\"Decisionnel.xml\"/>\n"
"  <volumes file=\"Volumes.xml\"/>\n"
"  <protections file=\"Protections.xml\"/>\n"
"  <dotation-natures file=\"DotationNatures.xml\"/>\n"
"  <objects file=\"Objets.xml\"/>\n"
"  <dotations file=\"Dotations.xml\"/>\n"
"  <launchers file=\"Lanceurs.xml\"/>\n"
"  <weapon-systems file=\"Armements.xml\"/>\n"
"  <sensors file=\"Capteurs.xml\"/>\n"
"  <components file=\"Composantes.xml\"/>\n"
"  <units file=\"Pions.xml\"/>\n"
"  <automats file=\"Automates.xml\"/>\n"
"  <nbc file=\"NBC.xml\"/>\n"
"  <fire file=\"Fire.xml\"/>\n"
"  <medical-treatment file=\"MedicalTreatment.xml\"/>\n"
"  <health file=\"Sante.xml\"/>\n"
"  <classeids file=\"IDClasses.xml\"/>\n"
"  <human-factors file=\"FacteursHumains.xml\"/>\n"
"  <breakdowns file=\"Pannes.xml\"/>\n"
"  <knowledge-groups file=\"GroupesConnaissance.xml\"/>\n"
"  <maintenance file=\"Maintenance.xml\"/>\n"
"  <supply file=\"Ravitaillement.xml\"/>\n"
"  <communications file=\"Communications.xml\"/>\n"
"  <pathfinder file=\"Pathfind.xml\"/>\n"
"  <populations file=\"Populations.xml\"/>\n"
"  <reports file=\"Reports.xml\"/>\n"
"  <models file=\"Modeles.xml\"/>\n"
"  <missions file=\"Missions.xml\"/>\n"
"</physical>";

// *****************************************************************************
// idclasses.xml
// *****************************************************************************
static const char* idClassesXml = 
"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
"<Classes>\n"
"    <Classe nom=\"Unite\"                                 id=\"1\" />\n"
"    <Classe nom=\"TirPion\"                               id=\"2\" />\n"
"    <Classe nom=\"TirPopulation\"                         id=\"227\" />\n"
"    <Classe nom=\"Lima\"                                  id=\"137\" />\n"
"    <Classe nom=\"Limite\"                                id=\"138\" />\n"
"    <Classe nom=\"Ordre\"                                 id=\"145\" />\n"
"    <Classe nom=\"GhostAgent\"                            id=\"158\" />\n"
"    <Classe nom=\"EffetsTirs\"                            id=\"188\" />\n"
"    <Classe nom=\"TraitementLogMaintenance\"              id=\"203\" />\n"
"    <Classe nom=\"TraitementLogSante\"                    id=\"204\" />\n"
"    <Classe nom=\"TraitementLogRavitaillement\"           id=\"201\" />\n"
"    <Classe nom=\"fosse anti char\"                       id=\"147\" />\n"
"    <Classe nom=\"abattis\"                               id=\"147\" />\n"
"    <Classe nom=\"barricade\"                             id=\"147\" />\n"
"    <Classe nom=\"bouchon mines\"                         id=\"147\" />\n"
"    <Classe nom=\"zone minee lineaire\"                   id=\"147\" />\n"
"    <Classe nom=\"zone minee par dispersion\"             id=\"147\" />\n"
"    <Classe nom=\"eboulement\"                            id=\"147\" />\n"
"    <Classe nom=\"destruction route\"                     id=\"147\" />\n"
"    <Classe nom=\"destruction pont\"                      id=\"147\" />\n"
"    <Classe nom=\"pont flottant continu\"                 id=\"168\" />\n"
"    <Classe nom=\"pont flottant discontinu\"              id=\"168\" />\n"
"    <Classe nom=\"poste tir\"                             id=\"166\" />\n"
"    <Classe nom=\"zone protegee\"                         id=\"166\" />\n"
"    <Classe nom=\"zone implantation canon\"               id=\"167\" />\n"
"    <Classe nom=\"zone implantation cobra\"               id=\"167\" />\n"
"    <Classe nom=\"zone implantation lrm\"                 id=\"167\" />\n"
"    <Classe nom=\"site franchissement\"                   id=\"168\" />\n"
"    <Classe nom=\"nuage nbc\"                             id=\"190\" />\n"
"    <Classe nom=\"site decontamination\"                  id=\"213\" />\n"
"    <Classe nom=\"plot ravitaillement\"                   id=\"189\" />\n"
"    <Classe nom=\"zone brouillage\"                       id=\"212\" />\n"
"    <Classe nom=\"rota\"                                  id=\"197\" />\n"
"    <Classe nom=\"zone NBC\"                              id=\"126\" />\n"
"    <Classe nom=\"aire poser\"                            id=\"210\" />\n"
"    <Classe nom=\"piste\"                                 id=\"209\" />\n"
"    <Classe nom=\"plateforme\"                            id=\"210\" />\n"
"    <Classe nom=\"zone mobilite amelioree\"               id=\"210\" />\n"
"    <Classe nom=\"zone poser helicoptere\"                id=\"210\" />\n"
"    <Classe nom=\"aire logistique\"                       id=\"210\" />\n"
"    <Classe nom=\"camp prisonniers\"                      id=\"207\" />\n"
"    <Classe nom=\"camp refugies\"                         id=\"207\" />\n"
"    <Classe nom=\"itineraire logistique\"                 id=\"211\" />\n"
"    <Classe nom=\"poste controle\"                        id=\"208\" />\n"
"    <Classe nom=\"terrain largage\"                       id=\"210\" />\n"
"    <Classe nom=\"zone interdite tir\"                    id=\"215\" />\n"
"    <Classe nom=\"zone interdite mouvement\"              id=\"215\" />\n"
"    <Classe nom=\"zone implantation mortier\"             id=\"167\" />\n"
"    <Classe nom=\"installation\"                          id=\"210\" />\n"
"    <Classe nom=\"fire\"                                  id=\"210\" />\n"
"    <Classe nom=\"emergency shelter\"                     id=\"210\" />\n"
"    <Classe nom=\"Population\"                            id=\"139\" />\n"
"    <Classe nom=\"PopulationConcentration\"               id=\"218\" />\n"
"    <Classe nom=\"PopulationFlux\"                        id=\"220\" />\n"
"    <Classe nom=\"ConnaissancePopulation\"                id=\"223\" />\n"
"    <Classe nom=\"ConnaissancePopulationConcentration\"   id=\"222\" />\n"
"    <Classe nom=\"ConnaissancePopulationFlux\"            id=\"221\" />\n"
"</Classes>\n";
