--
-- file name : ScipioAutomateMission.asn
--
-- Messages des différentes missions automate NBC
--

ScipioAutomateMission_NBC DEFINITIONS AUTOMATIC TAGS ::= BEGIN

IMPORTS ListAgent, Agent, Direction, OID, CoordUTM, max-uint64, max-uint32, max-uint16, 
        max-uint8, Point, Itineraire, EnumUnitIdentificationLevel, Segment, GDH, Localisation FROM ScipioBase;


Mission-Automate-NBC-ReconnaitreUnAxe ::= SEQUENCE
{    
}

Mission-Automate-NBC-ReconnaitreUneZone ::= SEQUENCE
{
    zone   Polygon
}       

Mission-Automate-NBC-ArmerUnSiteDeDecontamination ::= SEQUENCE
{
    site   Polygon
}       

Mission-Automate-NBC-DecontaminerUneZone ::= SEQUENCE
{
    zone   Polygon
}

Mission-Automate-NBC-ReconnaitreDesSitesROTA ::= SEQUENCE
{
    sites-ROTA ListKnowledgeObject
}
     
END -- ScipioAutomateMission_NBC
