--
-- file name : ScipioAutomateMission.asn
--
-- Messages des différentes missions automate Rens
--

ScipioAutomateMission_TRANS DEFINITIONS AUTOMATIC TAGS ::= BEGIN

IMPORTS ListAgent, Agent, Direction, OID, CoordUTM, max-uint64, max-uint32, max-uint16, 
        max-uint8, Polygon, ListPolygon, Point, Itineraire, EnumUnitIdentificationLevel, Segment, GDH, Localisation FROM ScipioBase;

Mission-Automate-TRANS-Commander ::= SEQUENCE
{
    zone-deploiement Polygon
}

END -- ScipioAutomateMission_TRANS
