--
-- file name : ScipioAutomateMission.asn
--
-- Messages des différentes missions automate génie
--

ScipioAutomateMission_GEN DEFINITIONS AUTOMATIC TAGS ::= BEGIN

IMPORTS ListAgent, Agent, Direction, OID, CoordUTM, max-uint64, max-uint32, 
        max-uint16, max-uint8, Point, ListPoint, EnumUnitIdentificationLevel, Segment, GDH, Localisation FROM ScipioBase
IMPORTS EnumMissionGenUrgence, EnumMissionGenSousTypeObstacle FROM ScipioObject;

-- Sous types

EnumMissionGenPriorite ::= ENUMERATED
{
    prioritaire,
    normal,
    peu-prioritaire
}

MissionGenObject ::= SEQUENCE
{
    type-obstacle           EnumObjectType,
    pos-obstacle            Localisation,
    oid-obstacle-planifie   OID,
    urgence                 EnumMissionGenUrgence          DEFAULT serie-complementaire,
    preliminaire            EnumMissionGenSousTypeObstacle DEFAULT preliminaire,
    priorite                EnumMissionGenPriorite
}

ListMissionGenObject ::= SEQUENCE OF MissionGenObject;


------------------------------------------
-- Mission GEN
------------------------------------------
Mission-Automate-GEN-SeDeployer ::= SEQUENCE
{
    zone-deploiement Polygon 
}

Mission-Automate-GEN-FaireFranchir ::= SEQUENCE
{
    sites-de-franchissement ListKnowledgeObject,
    zone-regroupement       Localisation
}

Mission-Automate-GEN-RealiserSystemeObstacles ::= SEQUENCE
{
    obstacles ListMissionGenObject
}

Mission-Automate-GEN-FranchirDeViveForce ::= SEQUENCE
{
    obstacles-a-franchir ListKnowledgeObject
}

Mission-Automate-GEN-RetablirItineraires ::= SEQUENCE
{
    itineraires ListItineraire
}

Mission-Automate-GEN-AmenagerAireStationnement ::= SEQUENCE
{
    travaux   ListMissionGenObject
}

Mission-Automate-GEN-AmenagerTerrainPoserSommaire ::= SEQUENCE
{
    terrain MissionGenObject
}

Mission-Automate-GEN-RealiserZonePoser ::= SEQUENCE
{
    zone MissionGenObject
}

Mission-Automate-GEN-ReconnaitreZoneDeploiement ::= SEQUENCE
{
    zone Polygon
}

Mission-Automate-GEN-RealiserCampPrisonniers ::= SEQUENCE
{
    camp    Polygon,
    tc2     Automate
}

Mission-Automate-GEN-RealiserCampRefugies ::= SEQUENCE
{
    camp    Polygon,
    tc2     Automate
}

Mission-Automate-GEN-RealiserPlatesformesSommairesDeDeploiementInitial ::= SEQUENCE
{
    plates-formes ListMissionGenObject
}

Mission-Automate-GEN-RealiserTravauxSommairesAuProfitPopulation ::= SEQUENCE
{
    travaux ListMissionGenObject
}

Mission-Automate-GEN-AppuyerDebarquementTroupes ::= SEQUENCE
{
    zones-debarquement ListMissionGenObject
}

Mission-Automate-GEN-OuvrirAxesProgression ::= SEQUENCE
{
    axes ListItineraire
}

END -- ScipioAutomateMission_GEN
