--
-- file name : ScipioBase.asn
--
-- Types de base
--

ScipioBase DEFINITIONS AUTOMATIC TAGS ::= BEGIN

--
-- Limits
--
max-uint64 INTEGER ::= 18446744073709551616
max-uint32 INTEGER ::= 4294967295
max-uint16 INTEGER ::= 65535
max-uint8  INTEGER ::= 255

--
-- Géométrie
--
EnumTypeLocalisation ::= ENUMERATED
{ 
    circle   (0), -- Circle
    ellipse  (1), -- Ellipse
    line     (2), -- Line 
    polygon  (3), -- Polygon
    point    (4), -- Point
    sector   (5)  -- Sector
}

CoordUTM ::= OCTET STRING (SIZE(15))

Localisation ::= SEQUENCE 
{
    type            EnumTypeLocalisation,
    vecteur-point   SEQUENCE OF CoordUTM
}

Point      ::= Localisation (WITH COMPONENTS {...,type(point)})
Line       ::= Localisation (WITH COMPONENTS {...,type(line)})
Itineraire ::= Localisation (WITH COMPONENTS {...,type(line)})
Polygon    ::= Localisation (WITH COMPONENTS {...,type(polygon)})
Segment    ::= Localisation (WITH COMPONENTS {type(line)   , vecteur-point (SIZE(2))})
Circle	   ::= Localisation (WITH COMPONENTS {type(circle) , vecteur-point (SIZE(2))}) -- Format : centre, point sur le cercle
Ellipse	   ::= Localisation (WITH COMPONENTS {type(ellipse), vecteur-point (SIZE(3))}) -- Format : centre, point petit axe, point grand axe
Sector	   ::= Localisation (WITH COMPONENTS {type(sector) , vecteur-point (SIZE(3))}) -- Format : centre, point 1, point 2 dans le sens trigo

ListLocalisation ::= SEQUENCE OF Localisation
ListPolygon      ::= SEQUENCE OF Polygon
ListItineraire   ::= SEQUENCE OF Itineraire
ListPoint        ::= SEQUENCE OF Point

--
-- Types
--
OID                 ::= INTEGER (0..max-uint32)
ListOID             ::= SEQUENCE OF OID
TirIndirect         ::= OID
TirDirect           ::= OID
Agent               ::= OID
Automate            ::= OID
Population          ::= OID
KnowledgeAgent      ::= OID
KnowledgeObject     ::= OID
ListAutomate        ::= SEQUENCE OF Automate 
ListAgent           ::= SEQUENCE OF Agent
ListKnowledgeAgent  ::= SEQUENCE OF KnowledgeAgent
ListKnowledgeObject ::= SEQUENCE OF KnowledgeObject
TypeEquipement      ::= OID
TypeDotation        ::= OID
TypePanne           ::= OID
TypePion            ::= OID
TypeAutomate        ::= OID
TypePopulation      ::= OID
Pourcentage         ::= INTEGER(0..100)
PourcentageLibre    ::= INTEGER(0..max-uint32)
Hauteur             ::= INTEGER(0..max-uint32)
Altitude            ::= INTEGER(0..max-uint32)
Vitesse             ::= INTEGER(0..max-uint32)
Angle               ::= INTEGER(0..360)
Direction           ::= INTEGER(0..<360)
GDH                 ::= SEQUENCE 
{
    datation        INTEGER (0..max-uint32),
    qualificatif    EnumGDH_Qualificatif 
}

EnumFamilleDotation ::= ENUMERATED
{
    munition (0),
    carburant(1),
    explosif (2),
    mine     (3),
    barbele  (4),
    piece    (5),
    ration   (6)
}

EnumFamilleMunition ::= ENUMERATED
{
    obus        (0),
    missile-air (1),
    missile-sol (2),
    mitraille   (3)
}

EnumGDH_Qualificatif ::= ENUMERATED
{
    at          (0),
    after       (1),
    as-of       (2),
    before      (3),
    cleared     (4),
    due         (5),
    end         (6),
    off         (7),
    on          (8),
    since       (9),
    start       (10),
    until       (11),
    wef         (12)
}

EnumUnitIdentificationLevel ::= ENUMERATED
{
    identifiee (0),
    reconnue   (1),
    detectee   (2),
    signale    (3) 
}

EnumUnitNatureWeapon ::= ENUMERATED 
{
    none                                (0),
    antichar                            (1),
    administration                      (2),
    defense-aerienne                    (3),
    centre-soutien-operations-aeriennes (4),
    blinde                              (5),
    aviation                            (6),
    cavalerie                           (7),
    genie                               (8),
    deminage                            (9),
    soutien-artillerie                  (10),
    artillerie                          (11),
    infanterie                          (12),
    guerre-information                  (13),
    forces-securite-interne             (14),
    execution-loi                       (15),
    soutien-atterrissage                (16),
    logistique                          (17),
    reparation                          (18),
    manoeuvre                           (19),
    medical                             (20),
    renseignement-militaire             (21),
    missile                             (22),
    nbc                                 (23),
    inconnue                            (24),
    non-specifiee                       (25),
    reconnaissance                      (26),
    transmissions                       (27),
    ravitaillement                      (28),
    tactical-air-control-party          (29),
    transport                           (30)
}

EnumUnitNatureSpecialization ::= ENUMERATED 
{
    none                                 (0),
    aerien                               (1),
    attaque-aerienne                     (2),
    aeroporte                            (3),
    blinde                               (4),
    compose                              (5),
    construction                         (6),
    dentiste                             (7),
    guerre-electronique                  (8),
    finance                              (9),
    voilure-fixe                         (10),
    terrestre                            (11),
    helicoptere                          (12),
    jag                                  (13),
    mecanise                             (14),
    police-militaire                     (15),
    motorise                             (16),
    naval                                (17),
    service-du-personnel                 (18),
    courrier                             (19),
    psychologique                        (20),
    chemin-de-fer                        (21),
    religieux                            (22),
    riverine                             (23),
    security-police                      (24),
    patrouille-cotiere                   (25),
    chirurgie                            (26),
    veterinaire                          (27),
    decollage-atterissage-vertical-court (28)

}

EnumUnitNatureQualifier  ::= ENUMERATED 
{
    none  (0),
    lourd (1),
    leger (2),
    moyen (3)
}

EnumUnitNatureCategory  ::= ENUMERATED 
{
    none               (0),
    combat             (1),
    soutien-logistique (2),
    combat-support     (3),
    inconnu            (4)

}

EnumUnitNatureMobility  ::= ENUMERATED 
{
    none                      (0),
    aeroporte                 (1),
    aerien-compose            (2),
    aerien-voilure-fixe       (3),
    aerien-plus-leger-que-air (4),
    aerien-ailes-rotatives    (5),
    aerien-amphibie           (6),
    animal-monte              (7),
    demonte                   (8),
    terrestre-chemin-de-fer   (9),
    terrestre-auto-propulse   (10),
    terrestre-chenille        (11),
    terrestre-remorque        (12),
    terrestre-roues           (13),
    maritime-sous-marin       (14),
    maritime-surface          (15),
    inconnu                   (16)
}

EnumUnitCapaciteMission ::= ENUMERATED
{
    civilian-law-enforcement                  (0),
    command-operations                        (1),
    couverture-aerienne                       (2),
    joint-intelligence                        (3),
    morale-welfare-recreation                 (4),
    reglage-electronique                      (5),
    remplacement                              (6),
    service-mortuaire                         (7),
    signals-intelligence                      (8),
    theatre-missile-defence                   (9),
    utilitaire                                (10),
    aeroporte                                 (11),
    affaires-publiques                        (12),
    affaires-publiques-communication          (13),
    affaires-publiques-joint-information      (14),
    alpin                                     (15),
    amphibie                                  (16),
    arctique                                  (17),
    artillerie-reconnaissance                 (18),
    attaque                                   (19),
    attaque-aerienne                          (20),
    c2                                        (21),
    chemin-de-fer                             (22),
    ciblage                                   (23),
    contre-espionnage                         (24),
    eclairage                                 (25),
    entretien                                 (26),
    entretien-materiel                        (27),
    entretien-missile                         (28),
    entretien-opto-electronique               (29),
    espionnage                                (30),
    espionnage-militaire-aerial-exploitation  (31),
    espionnage-militaire-operation            (32),
    espionnage-militaire-tactical-exploitation(33),
    evacuation-sanitaire                      (34),
    finance                                   (35),
    genie-combat                              (36),
    genie-construction                        (37),
    genie-construction-navale                 (38),
    guerre-electronique                       (39),
    guerre-electronique-interception          (40),
    guerre-electronique-brouillage            (41),
    guerre-electronique-detection             (42),
    interrogation                             (43),
    main-d-oeuvre                             (44),
    maintien-de-la-paix                       (45),
    marine                                    (46),
    mine-de-contre-mesure                     (47),
    nbc-biologique                            (48),
    nbc-chimique                              (49),
    nbc-chimique-fumee                        (50),
    nbc-decontamination                       (51),
    nbc-decontamination-chimique              (52),
    nbc-nucleaire                             (53),
    non-renseigne                             (54),
    observation                               (55),
    observation-capteur                       (56),
    observation-longue-portee                 (57),
    observation-meteo                         (58),
    observation-module-terrestre              (59),
    purification-de-l-eau                     (60),
    ravitaillement-class-i                    (61),
    ravitaillement-class-ii                   (62),
    ravitaillement-class-iii-aviation         (63),
    ravitaillement-class-iii                  (64),
    ravitaillement-class-iv                   (65),
    ravitaillement-class-v                    (66),
    ravitaillement-eau                        (67),
    ravitaillement-blanchisserie-bain         (68),
    recherche-et-sauvetage                    (69),
    reconnaissance                            (70),
    reconnaissance-aerienne-tactique          (71),
    recuperation                              (72),
    service-du-personnel                      (73),
    service-juridique                         (74),
    support-aerien-rapproche                  (75),
    transmissions-forward-communications      (76),
    transmissions-node-centre                 (77),
    transmissions-node-large-extension        (78),
    transmissions-node-small-extension        (79),
    transmissions-radio-relay                 (80),
    transmissions-radio-tactical-satellite    (81),
    transmissions-radio-teletype              (82),
    transmissions-support                     (83),
    transmissions-radio                       (84),
    transport-allocation-des-mouvements       (85),
    transport-apod-apoe                       (86),
    transport-spod-spoe                       (87),
    transport-missile                         (88),
    verrouillage-de-cible                     (89),
    verrouillage-de-cible-flash               (90),
    verrouillage-de-cible-radar               (91),
    verrouillage-de-cible-sonore              (92) 
}

EnumNatureLevel ::= ENUMERATED
{
    none        (0),  -- None
    o           (1),  -- Team
    oo          (2),  -- Group/Patrol/Squad
    ooo         (3),  -- Section/platoon
    i           (4),  -- Company
    ii          (5),  -- Battalion
    iii         (6),  -- Regiment
    x           (7),  -- Brigade
    xx          (8),  -- Division
    xxx         (9),  -- Army corps
    xxxx        (10), -- Field army (obsolete)
    xxxxx       (11)  -- Army group/front (obsolete)
}

NatureAtlas ::= BIT STRING 
{ 
    blinde          (0), 
    ass             (1), 
    pc              (2), 
    log             (3), 
    mortier         (4), 
    lance-roquette  (5), 
    vehicule        (6), 
    personnel-a-pied(7), 
    helicoptere     (8), 
    indefini        (9), 
    asa             (10),
    none            (11) 
}

EnumHumanWound ::= ENUMERATED 
{
    non-blesse            (0),
    mort                  (1),
    blesse-urgence-1      (2),
    blesse-urgence-2      (3),
    blesse-urgence-3      (4),
    blesse-urgence-extreme(5)
}

EnumHumanRank ::= ENUMERATED
{
    officier    (0),
    sous-officer(1),
    mdr         (2)
}

EnumTempsBordee ::= ENUMERATED
{
    temps-8-heures    (0),   
    temps-12-heures   (1),
    temps-16-heures   (2),
    temps-20-heures   (3),
    temps-24-heures   (4)
}
                    

END -- ScipioBase
