--
-- file name : ScipioPionMission_Rens.asn
--

ScipioPionMission_TRANS DEFINITIONS AUTOMATIC TAGS ::= BEGIN

IMPORTS ListAgent, Agent, KnowledgeAgent, Direction, OID, CoordUTM, max-uint64, max-uint32, max-uint16, 
        max-uint8, Point, Itineraire, EnumUnitIdentificationLevel, Segment, GDH FROM ScipioBase;

Mission-Pion-TRANS-EtablirGererLiaison ::= SEQUENCE
{
    position-deploiement Point
}

END -- ScipioPionMission_TRANS
