// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2004 Mathématiques Appliquées SA (MASA)
//
// *****************************************************************************
//
// $Created: AGN 2004-04-26 $
// $Archive: /MVW_v10/Build/SDK/AGR/src/AGR_MOS_MissionConverter_Skeleton.cpp $
// $Author: Agn $
// $Modtime: 26/04/04 14:29 $
// $Revision: 1 $
// $Workfile: AGR_MOS_MissionConverter_Skeleton.cpp $
//
// *****************************************************************************

MOS_Tools::T_MissionConverter MOS_Tools::missionConverter_[] =
{
    T_MissionConverter("Automate ABC ArmerPointDeControle", "Automate ABC ArmerPointDeControle", eMission_Automate_ABC_ArmerPointDeControle ),
    T_MissionConverter("Automate ABC OrganiserAccueilColonneRefugies", "Automate ABC OrganiserAccueilColonneRefugies", eMission_Automate_ABC_OrganiserAccueilColonneRefugies ),
    T_MissionConverter("Automate ABC ProtegerPC", "Automate ABC ProtegerPC", eMission_Automate_ABC_ProtegerPC ),
    T_MissionConverter("Automate ABC Appuyer", "Automate ABC Appuyer", eMission_Automate_ABC_Appuyer ),
    T_MissionConverter("Automate ABC Attaquer", "Automate ABC Attaquer", eMission_Automate_ABC_Attaquer ),
    T_MissionConverter("Automate ABC ContreAttaquer", "Automate ABC ContreAttaquer", eMission_Automate_ABC_ContreAttaquer ),
    T_MissionConverter("Automate ABC Controler", "Automate ABC Controler", eMission_Automate_ABC_Controler ),
    T_MissionConverter("Automate ABC Couvrir", "Automate ABC Couvrir", eMission_Automate_ABC_Couvrir ),
    T_MissionConverter("Automate ABC DonnerCoupArret", "Automate ABC DonnerCoupArret", eMission_Automate_ABC_DonnerCoupArret ),
    T_MissionConverter("Automate ABC Eclairer", "Automate ABC Eclairer", eMission_Automate_ABC_Eclairer ),
    T_MissionConverter("Automate ABC EffectuerRaid", "Automate ABC EffectuerRaid", eMission_Automate_ABC_EffectuerRaid ),
    T_MissionConverter("Automate ABC Interdire", "Automate ABC Interdire", eMission_Automate_ABC_Interdire ),
    T_MissionConverter("Automate ABC Jalonner", "Automate ABC Jalonner", eMission_Automate_ABC_Jalonner ),
    T_MissionConverter("Automate ABC PrendrePreciserContact", "Automate ABC PrendrePreciserContact", eMission_Automate_ABC_PrendrePreciserContact ),
    T_MissionConverter("Automate ABC Reconnaitre", "Automate ABC Reconnaitre", eMission_Automate_ABC_Reconnaitre ),
    T_MissionConverter("Automate ABC ReconnaitrePoint", "Automate ABC ReconnaitrePoint", eMission_Automate_ABC_ReconnaitrePoint ),
    T_MissionConverter("Automate ABC Reduire", "Automate ABC Reduire", eMission_Automate_ABC_Reduire ),
    T_MissionConverter("Automate ABC ReleverEnDepassant", "Automate ABC ReleverEnDepassant", eMission_Automate_ABC_ReleverEnDepassant ),
    T_MissionConverter("Automate ABC Semparer", "Automate ABC Semparer", eMission_Automate_ABC_Semparer ),
    T_MissionConverter("Automate ABC Tenir", "Automate ABC Tenir", eMission_Automate_ABC_Tenir ),
    T_MissionConverter("Automate ABC Soutenir", "Automate ABC Soutenir", eMission_Automate_ABC_Soutenir ),
    T_MissionConverter("Automate ABC Surveiller", "Automate ABC Surveiller", eMission_Automate_ABC_Surveiller ),
    T_MissionConverter("Automate ABC FlancGarder", "Automate ABC FlancGarder", eMission_Automate_ABC_FlancGarder ),
    T_MissionConverter("Automate ABC RenseignerSur", "Automate ABC RenseignerSur", eMission_Automate_ABC_RenseignerSur ),
    T_MissionConverter("Automate ABC Fixer", "Automate ABC Fixer", eMission_Automate_ABC_Fixer ),
    T_MissionConverter("Automate ABC Freiner", "Automate ABC Freiner", eMission_Automate_ABC_Freiner ),
    T_MissionConverter("Automate ABC SurveillerItineraire", "Automate ABC SurveillerItineraire", eMission_Automate_ABC_SurveillerItineraire ),
    T_MissionConverter("Automate ABC RenseignerSurUnAxe", "Automate ABC RenseignerSurUnAxe", eMission_Automate_ABC_RenseignerSurUnAxe ),
    T_MissionConverter("Automate ABC RecueillirUnite", "Automate ABC RecueillirUnite", eMission_Automate_ABC_RecueillirUnite ),
    T_MissionConverter("Automate ABC EscorterUnConvoi", "Automate ABC EscorterUnConvoi", eMission_Automate_ABC_EscorterUnConvoi ),
    T_MissionConverter("Pion ALAT EvacuationSanitaire", "Pion ALAT EvacuationSanitaire", eMission_Pion_ALAT_EvacuationSanitaire ),
    T_MissionConverter("Pion ALAT ReconnaitreDansLaProfondeur", "Pion ALAT ReconnaitreDansLaProfondeur", eMission_Pion_ALAT_ReconnaitreDansLaProfondeur ),
    T_MissionConverter("Pion ALAT ReconnaitreContourEnnemi", "Pion ALAT ReconnaitreContourEnnemi", eMission_Pion_ALAT_ReconnaitreContourEnnemi ),
    T_MissionConverter("Pion ALAT DetruireNeutraliserDansZone", "Pion ALAT DetruireNeutraliserDansZone", eMission_Pion_ALAT_DetruireNeutraliserDansZone ),
    T_MissionConverter("Pion ALAT DetruireAeromobile", "Pion ALAT DetruireAeromobile", eMission_Pion_ALAT_DetruireAeromobile ),
    T_MissionConverter("Pion ALAT Freiner", "Pion ALAT Freiner", eMission_Pion_ALAT_Freiner ),
    T_MissionConverter("Pion ALAT Jalonner", "Pion ALAT Jalonner", eMission_Pion_ALAT_Jalonner ),
    T_MissionConverter("Pion ALAT Escorter", "Pion ALAT Escorter", eMission_Pion_ALAT_Escorter ),
    T_MissionConverter("Pion ALAT Heliporter", "Pion ALAT Heliporter", eMission_Pion_ALAT_Heliporter ),
    T_MissionConverter("Pion ALAT HeliporterHelitransporterPlotRavitaillement", "Pion ALAT HeliporterHelitransporterPlotRavitaillement", eMission_Pion_ALAT_HeliporterHelitransporterPlotRavitaillement ),
    T_MissionConverter("Pion ALAT Helitransporter", "Pion ALAT Helitransporter", eMission_Pion_ALAT_Helitransporter ),
    T_MissionConverter("Pion ALAT EffectuerRechercheEtSauvetage", "Pion ALAT EffectuerRechercheEtSauvetage", eMission_Pion_ALAT_EffectuerRechercheEtSauvetage ),
    T_MissionConverter("Pion ALAT IMEX", "Pion ALAT IMEX", eMission_Pion_ALAT_IMEX ),
    T_MissionConverter("Pion ALAT Eclairer", "Pion ALAT Eclairer", eMission_Pion_ALAT_Eclairer ),
    T_MissionConverter("Pion ALAT Surveiller", "Pion ALAT Surveiller", eMission_Pion_ALAT_Surveiller ),
    T_MissionConverter("Pion ALAT AppuyerDirectAuContact", "Pion ALAT AppuyerDirectAuContact", eMission_Pion_ALAT_AppuyerDirectAuContact ),
    T_MissionConverter("Pion ALAT Couvrir", "Pion ALAT Couvrir", eMission_Pion_ALAT_Couvrir ),
    T_MissionConverter("Pion ALAT Attaquer", "Pion ALAT Attaquer", eMission_Pion_ALAT_Attaquer ),
    T_MissionConverter("Automate ALAT Heliporter", "Automate ALAT Heliporter", eMission_Automate_ALAT_Heliporter ),
    T_MissionConverter("Automate ALAT Jalonner", "Automate ALAT Jalonner", eMission_Automate_ALAT_Jalonner ),
    T_MissionConverter("Automate ALAT Helitransporter", "Automate ALAT Helitransporter", eMission_Automate_ALAT_Helitransporter ),
    T_MissionConverter("Automate ALAT ExtrairePersonnel", "Automate ALAT ExtrairePersonnel", eMission_Automate_ALAT_ExtrairePersonnel ),
    T_MissionConverter("Automate ALAT Appuyer", "Automate ALAT Appuyer", eMission_Automate_ALAT_Appuyer ),
    T_MissionConverter("Automate ALAT Couvrir", "Automate ALAT Couvrir", eMission_Automate_ALAT_Couvrir ),
    T_MissionConverter("Automate ALAT Surveiller", "Automate ALAT Surveiller", eMission_Automate_ALAT_Surveiller ),
    T_MissionConverter("Automate ALAT Reconnaitre", "Automate ALAT Reconnaitre", eMission_Automate_ALAT_Reconnaitre ),
    T_MissionConverter("Automate ALAT Freiner", "Automate ALAT Freiner", eMission_Automate_ALAT_Freiner ),
    T_MissionConverter("Automate ALAT Escorter", "Automate ALAT Escorter", eMission_Automate_ALAT_Escorter ),
    T_MissionConverter("Automate ALAT Attaquer", "Automate ALAT Attaquer", eMission_Automate_ALAT_Attaquer ),
    T_MissionConverter("Automate ALAT RecueillirFormationAeromobile", "Automate ALAT RecueillirFormationAeromobile", eMission_Automate_ALAT_RecueillirFormationAeromobile ),
    T_MissionConverter("Automate ALAT AttaquerFormationAeromobile", "Automate ALAT AttaquerFormationAeromobile", eMission_Automate_ALAT_AttaquerFormationAeromobile ),
    T_MissionConverter("Automate ALAT DonnerCoupArret", "Automate ALAT DonnerCoupArret", eMission_Automate_ALAT_DonnerCoupArret ),
    T_MissionConverter("Automate ALAT DetruireNeutraliserDansProfondeur", "Automate ALAT DetruireNeutraliserDansProfondeur", eMission_Automate_ALAT_DetruireNeutraliserDansProfondeur ),
    T_MissionConverter("Automate ALAT DetruireNeutraliserDansZone", "Automate ALAT DetruireNeutraliserDansZone", eMission_Automate_ALAT_DetruireNeutraliserDansZone ),
    T_MissionConverter("Automate ALAT EffectuerRechercheEtSauvetage", "Automate ALAT EffectuerRechercheEtSauvetage", eMission_Automate_ALAT_EffectuerRechercheEtSauvetage ),
    T_MissionConverter("Automate ASA DefendreZone", "Automate ASA DefendreZone", eMission_Automate_ASA_DefendreZone ),
    T_MissionConverter("Automate ASA DefendreSite", "Automate ASA DefendreSite", eMission_Automate_ASA_DefendreSite ),
    T_MissionConverter("Automate ASA Surveiller", "Automate ASA Surveiller", eMission_Automate_ASA_Surveiller ),
    T_MissionConverter("Automate ASA DefendreItineraire", "Automate ASA DefendreItineraire", eMission_Automate_ASA_DefendreItineraire ),
    T_MissionConverter("Automate ASA MISTRAL DefendreZone", "Automate ASA MISTRAL DefendreZone", eMission_Automate_ASA_MISTRAL_DefendreZone ),
    T_MissionConverter("Automate ASA MISTRAL DefendreSite", "Automate ASA MISTRAL DefendreSite", eMission_Automate_ASA_MISTRAL_DefendreSite ),
    T_MissionConverter("Automate ASA MISTRAL Surveiller", "Automate ASA MISTRAL Surveiller", eMission_Automate_ASA_MISTRAL_Surveiller ),
    T_MissionConverter("Automate ASA HAWK DefendreZone", "Automate ASA HAWK DefendreZone", eMission_Automate_ASA_HAWK_DefendreZone ),
    T_MissionConverter("Automate ASA HAWK DefendreSite", "Automate ASA HAWK DefendreSite", eMission_Automate_ASA_HAWK_DefendreSite ),
    T_MissionConverter("Automate ASA HAWK Surveiller", "Automate ASA HAWK Surveiller", eMission_Automate_ASA_HAWK_Surveiller ),
    T_MissionConverter("Automate ASA DefendreUnites", "Automate ASA DefendreUnites", eMission_Automate_ASA_DefendreUnites ),
    T_MissionConverter("Automate ASS SeDeployer", "Automate ASS SeDeployer", eMission_Automate_ASS_SeDeployer ),
    T_MissionConverter("Automate ASS ReconnaitreZonesDeploiement", "Automate ASS ReconnaitreZonesDeploiement", eMission_Automate_ASS_ReconnaitreZonesDeploiement ),
    T_MissionConverter("Automate ASS AcquerirObjectifs", "Automate ASS AcquerirObjectifs", eMission_Automate_ASS_AcquerirObjectifs ),
    T_MissionConverter("Automate GEN SeDeployer", "Automate GEN SeDeployer", eMission_Automate_GEN_SeDeployer ),
    T_MissionConverter("Automate GEN FaireFranchir", "Automate GEN FaireFranchir", eMission_Automate_GEN_FaireFranchir ),
    T_MissionConverter("Automate GEN RealiserSystemeObstacles", "Automate GEN RealiserSystemeObstacles", eMission_Automate_GEN_RealiserSystemeObstacles ),
    T_MissionConverter("Automate GEN FranchirDeViveForce", "Automate GEN FranchirDeViveForce", eMission_Automate_GEN_FranchirDeViveForce ),
    T_MissionConverter("Automate GEN RetablirItineraires", "Automate GEN RetablirItineraires", eMission_Automate_GEN_RetablirItineraires ),
    T_MissionConverter("Automate GEN AmenagerAireStationnement", "Automate GEN AmenagerAireStationnement", eMission_Automate_GEN_AmenagerAireStationnement ),
    T_MissionConverter("Automate GEN AmenagerTerrainPoserSommaire", "Automate GEN AmenagerTerrainPoserSommaire", eMission_Automate_GEN_AmenagerTerrainPoserSommaire ),
    T_MissionConverter("Automate GEN RealiserZonePoser", "Automate GEN RealiserZonePoser", eMission_Automate_GEN_RealiserZonePoser ),
    T_MissionConverter("Automate GEN ReconnaitreZoneDeploiement", "Automate GEN ReconnaitreZoneDeploiement", eMission_Automate_GEN_ReconnaitreZoneDeploiement ),
    T_MissionConverter("Automate GEN RealiserCampPrisonniers", "Automate GEN RealiserCampPrisonniers", eMission_Automate_GEN_RealiserCampPrisonniers ),
    T_MissionConverter("Automate GEN RealiserCampRefugies", "Automate GEN RealiserCampRefugies", eMission_Automate_GEN_RealiserCampRefugies ),
    T_MissionConverter("Automate GEN RealiserPlatesformesSommairesDeDeploiementInitial", "Automate GEN RealiserPlatesformesSommairesDeDeploiementInitial", eMission_Automate_GEN_RealiserPlatesformesSommairesDeDeploiementInitial ),
    T_MissionConverter("Automate GEN RealiserTravauxSommairesAuProfitPopulation", "Automate GEN RealiserTravauxSommairesAuProfitPopulation", eMission_Automate_GEN_RealiserTravauxSommairesAuProfitPopulation ),
    T_MissionConverter("Automate GEN AppuyerDebarquementTroupes", "Automate GEN AppuyerDebarquementTroupes", eMission_Automate_GEN_AppuyerDebarquementTroupes ),
    T_MissionConverter("Automate GEN OuvrirAxesProgression", "Automate GEN OuvrirAxesProgression", eMission_Automate_GEN_OuvrirAxesProgression ),
    T_MissionConverter("Automate INF AttaquerSouplesse", "Automate INF AttaquerSouplesse", eMission_Automate_INF_AttaquerSouplesse ),
    T_MissionConverter("Automate INF Appuyer", "Automate INF Appuyer", eMission_Automate_INF_Appuyer ),
    T_MissionConverter("Automate INF Controler", "Automate INF Controler", eMission_Automate_INF_Controler ),
    T_MissionConverter("Automate INF Couvrir", "Automate INF Couvrir", eMission_Automate_INF_Couvrir ),
    T_MissionConverter("Automate INF DonnerCoupArret", "Automate INF DonnerCoupArret", eMission_Automate_INF_DonnerCoupArret ),
    T_MissionConverter("Automate INF Eclairer", "Automate INF Eclairer", eMission_Automate_INF_Eclairer ),
    T_MissionConverter("Automate INF FlancGarder", "Automate INF FlancGarder", eMission_Automate_INF_FlancGarder ),
    T_MissionConverter("Automate INF Freiner", "Automate INF Freiner", eMission_Automate_INF_Freiner ),
    T_MissionConverter("Automate INF Harceler", "Automate INF Harceler", eMission_Automate_INF_Harceler ),
    T_MissionConverter("Automate INF Interdire", "Automate INF Interdire", eMission_Automate_INF_Interdire ),
    T_MissionConverter("Automate INF MenerDefenseUsure", "Automate INF MenerDefenseUsure", eMission_Automate_INF_MenerDefenseUsure ),
    T_MissionConverter("Automate INF PrendrePreciserMaintenirContact", "Automate INF PrendrePreciserMaintenirContact", eMission_Automate_INF_PrendrePreciserMaintenirContact ),
    T_MissionConverter("Automate INF ReconnaissanceOffensive", "Automate INF ReconnaissanceOffensive", eMission_Automate_INF_ReconnaissanceOffensive ),
    T_MissionConverter("Automate INF RecueillirUnite", "Automate INF RecueillirUnite", eMission_Automate_INF_RecueillirUnite ),
    T_MissionConverter("Automate INF Reduire", "Automate INF Reduire", eMission_Automate_INF_Reduire ),
    T_MissionConverter("Automate INF Relever", "Automate INF Relever", eMission_Automate_INF_Relever ),
    T_MissionConverter("Automate INF RompreContact", "Automate INF RompreContact", eMission_Automate_INF_RompreContact ),
    T_MissionConverter("Automate INF Surveiller", "Automate INF Surveiller", eMission_Automate_INF_Surveiller ),
    T_MissionConverter("Automate INF Semparer", "Automate INF Semparer", eMission_Automate_INF_Semparer ),
    T_MissionConverter("Automate INF Fixer", "Automate INF Fixer", eMission_Automate_INF_Fixer ),
    T_MissionConverter("Automate INF AttaquerEnTerrainDifficile", "Automate INF AttaquerEnTerrainDifficile", eMission_Automate_INF_AttaquerEnTerrainDifficile ),
    T_MissionConverter("Automate INF BarrerDirection", "Automate INF BarrerDirection", eMission_Automate_INF_BarrerDirection ),
    T_MissionConverter("Automate INF DefendreFerme", "Automate INF DefendreFerme", eMission_Automate_INF_DefendreFerme ),
    T_MissionConverter("Automate INF Tenir", "Automate INF Tenir", eMission_Automate_INF_Tenir ),
    T_MissionConverter("Automate INF AppuyerUnFreinage", "Automate INF AppuyerUnFreinage", eMission_Automate_INF_AppuyerUnFreinage ),
    T_MissionConverter("Automate INF AppuyerUneAttaque", "Automate INF AppuyerUneAttaque", eMission_Automate_INF_AppuyerUneAttaque ),
    T_MissionConverter("Automate INF Soutenir", "Automate INF Soutenir", eMission_Automate_INF_Soutenir ),
    T_MissionConverter("Automate LOG SeDeployer", "Automate LOG SeDeployer", eMission_Automate_LOG_SeDeployer ),
    T_MissionConverter("Automate LOG AppuyerMouvement", "Automate LOG AppuyerMouvement", eMission_Automate_LOG_AppuyerMouvement ),
    T_MissionConverter("Automate LOG ReconnaitreItineraire", "Automate LOG ReconnaitreItineraire", eMission_Automate_LOG_ReconnaitreItineraire ),
    T_MissionConverter("Automate LOG Surveiller", "Automate LOG Surveiller", eMission_Automate_LOG_Surveiller ),
    T_MissionConverter("Automate LOG TransporterFormationBlindee", "Automate LOG TransporterFormationBlindee", eMission_Automate_LOG_TransporterFormationBlindee ),
    T_MissionConverter("Automate LOG AppuyerMouvementDansZone", "Automate LOG AppuyerMouvementDansZone", eMission_Automate_LOG_AppuyerMouvementDansZone ),
    T_MissionConverter("Automate LOG MettreEnOeuvreZoneStationnement", "Automate LOG MettreEnOeuvreZoneStationnement", eMission_Automate_LOG_MettreEnOeuvreZoneStationnement ),
    T_MissionConverter("Automate LOG AppuyerFranchissementDansZone", "Automate LOG AppuyerFranchissementDansZone", eMission_Automate_LOG_AppuyerFranchissementDansZone ),
    T_MissionConverter("Automate LOG BloquerZone", "Automate LOG BloquerZone", eMission_Automate_LOG_BloquerZone ),
    T_MissionConverter("Automate LOG ReconnaitreZoneContaminee", "Automate LOG ReconnaitreZoneContaminee", eMission_Automate_LOG_ReconnaitreZoneContaminee ),
    T_MissionConverter("Automate LOG ReconnaitreZoneDeDeploiement", "Automate LOG ReconnaitreZoneDeDeploiement", eMission_Automate_LOG_ReconnaitreZoneDeDeploiement ),
    T_MissionConverter("Automate LOG ArmerPIAs", "Automate LOG ArmerPIAs", eMission_Automate_LOG_ArmerPIAs ),
    T_MissionConverter("Automate Test MoveTo", "Automate Test MoveTo", eMission_Automate_Test_MoveTo ),
    T_MissionConverter("Automate Decrocher", "Automate Decrocher", eMission_Automate_Decrocher ),
    T_MissionConverter("Automate ReleverSurPlace", "Automate ReleverSurPlace", eMission_Automate_ReleverSurPlace ),
    T_MissionConverter("Automate FaireMouvement", "Automate FaireMouvement", eMission_Automate_FaireMouvement ),
    T_MissionConverter("Automate SeFaireDecontaminer", "Automate SeFaireDecontaminer", eMission_Automate_SeFaireDecontaminer ),
    T_MissionConverter("Automate Franchir", "Automate Franchir", eMission_Automate_Franchir ),
    T_MissionConverter("Automate Stationner", "Automate Stationner", eMission_Automate_Stationner ),
    T_MissionConverter("Automate SeFaireTransporter", "Automate SeFaireTransporter", eMission_Automate_SeFaireTransporter ),
    T_MissionConverter("Automate SeRecompleter", "Automate SeRecompleter", eMission_Automate_SeRecompleter ),
    T_MissionConverter("Automate SeRendre", "Automate SeRendre", eMission_Automate_SeRendre ),
    T_MissionConverter("Automate FaireMouvementVersCampRefugies", "Automate FaireMouvementVersCampRefugies", eMission_Automate_FaireMouvementVersCampRefugies ),
    T_MissionConverter("Automate Generique", "Automate Generique", eMission_Automate_Generique ),
    T_MissionConverter("Automate NBC ReconnaitreUnAxe", "Automate NBC ReconnaitreUnAxe", eMission_Automate_NBC_ReconnaitreUnAxe ),
    T_MissionConverter("Automate NBC ReconnaitreUneZone", "Automate NBC ReconnaitreUneZone", eMission_Automate_NBC_ReconnaitreUneZone ),
    T_MissionConverter("Automate NBC ArmerUnSiteDeDecontamination", "Automate NBC ArmerUnSiteDeDecontamination", eMission_Automate_NBC_ArmerUnSiteDeDecontamination ),
    T_MissionConverter("Automate NBC DecontaminerUneZone", "Automate NBC DecontaminerUneZone", eMission_Automate_NBC_DecontaminerUneZone ),
    T_MissionConverter("Automate NBC ReconnaitreDesSitesROTA", "Automate NBC ReconnaitreDesSitesROTA", eMission_Automate_NBC_ReconnaitreDesSitesROTA ),
    T_MissionConverter("Automate RENS ROHUM RenseignerSur", "Automate RENS ROHUM RenseignerSur", eMission_Automate_RENS_ROHUM_RenseignerSur ),
    T_MissionConverter("Automate RENS ROHUM OrienterGuider", "Automate RENS ROHUM OrienterGuider", eMission_Automate_RENS_ROHUM_OrienterGuider ),
    T_MissionConverter("Automate RENS ROHUM SExfiltrer", "Automate RENS ROHUM SExfiltrer", eMission_Automate_RENS_ROHUM_SExfiltrer ),
    T_MissionConverter("Automate RENS ROIM CL289 RenseignerSur", "Automate RENS ROIM CL289 RenseignerSur", eMission_Automate_RENS_ROIM_CL289_RenseignerSur ),
    T_MissionConverter("Automate RENS ROIM SDTI RenseignerSur", "Automate RENS ROIM SDTI RenseignerSur", eMission_Automate_RENS_ROIM_SDTI_RenseignerSur ),
    T_MissionConverter("Automate RENS ROEM Appuyer", "Automate RENS ROEM Appuyer", eMission_Automate_RENS_ROEM_Appuyer ),
    T_MissionConverter("Automate RENS ROEM RenseignerSur", "Automate RENS ROEM RenseignerSur", eMission_Automate_RENS_ROEM_RenseignerSur ),
    T_MissionConverter("Automate RENS RADINT RenseignerSur", "Automate RENS RADINT RenseignerSur", eMission_Automate_RENS_RADINT_RenseignerSur ),
    T_MissionConverter("Automate TRANS Commander", "Automate TRANS Commander", eMission_Automate_TRANS_Commander ),
    T_MissionConverter("Pion ASA DefendreSite", "Pion ASA DefendreSite", eMission_Pion_ASA_DefendreSite ),
    T_MissionConverter("Pion ASA DefendreSiteAPartirPosition", "Pion ASA DefendreSiteAPartirPosition", eMission_Pion_ASA_DefendreSiteAPartirPosition ),
    T_MissionConverter("Pion ASA DefendreZone", "Pion ASA DefendreZone", eMission_Pion_ASA_DefendreZone ),
    T_MissionConverter("Pion ASA DefendreZoneAPartirPosition", "Pion ASA DefendreZoneAPartirPosition", eMission_Pion_ASA_DefendreZoneAPartirPosition ),
    T_MissionConverter("Pion ASA Surveiller", "Pion ASA Surveiller", eMission_Pion_ASA_Surveiller ),
    T_MissionConverter("Pion ASA DefendreUnites", "Pion ASA DefendreUnites", eMission_Pion_ASA_DefendreUnites ),
    T_MissionConverter("Pion ASA MISTRAL DefendreSite", "Pion ASA MISTRAL DefendreSite", eMission_Pion_ASA_MISTRAL_DefendreSite ),
    T_MissionConverter("Pion ASA MISTRAL DefendreSiteAPartirPosition", "Pion ASA MISTRAL DefendreSiteAPartirPosition", eMission_Pion_ASA_MISTRAL_DefendreSiteAPartirPosition ),
    T_MissionConverter("Pion ASA MISTRAL DefendreZone", "Pion ASA MISTRAL DefendreZone", eMission_Pion_ASA_MISTRAL_DefendreZone ),
    T_MissionConverter("Pion ASA MISTRAL DefendreZoneAPartirPosition", "Pion ASA MISTRAL DefendreZoneAPartirPosition", eMission_Pion_ASA_MISTRAL_DefendreZoneAPartirPosition ),
    T_MissionConverter("Pion ASA MISTRAL Surveiller", "Pion ASA MISTRAL Surveiller", eMission_Pion_ASA_MISTRAL_Surveiller ),
    T_MissionConverter("Pion ASS AssurerMiseEnOeuvre", "Pion ASS AssurerMiseEnOeuvre", eMission_Pion_ASS_AssurerMiseEnOeuvre ),
    T_MissionConverter("Pion ASS AssurerMiseEnOeuvreSurPosition", "Pion ASS AssurerMiseEnOeuvreSurPosition", eMission_Pion_ASS_AssurerMiseEnOeuvreSurPosition ),
    T_MissionConverter("Pion ASS ReconnaitreZoneDeploiement", "Pion ASS ReconnaitreZoneDeploiement", eMission_Pion_ASS_ReconnaitreZoneDeploiement ),
    T_MissionConverter("Pion ASS AcquerirLanceursEni", "Pion ASS AcquerirLanceursEni", eMission_Pion_ASS_AcquerirLanceursEni ),
    T_MissionConverter("Pion ASS EO AcquerirObjectifs", "Pion ASS EO AcquerirObjectifs", eMission_Pion_ASS_EO_AcquerirObjectifs ),
    T_MissionConverter("Pion ASS EOP AcquerirObjectifs", "Pion ASS EOP AcquerirObjectifs", eMission_Pion_ASS_EOP_AcquerirObjectifs ),
    T_MissionConverter("Pion ASS RATAC AcquerirObjectifs", "Pion ASS RATAC AcquerirObjectifs", eMission_Pion_ASS_RATAC_AcquerirObjectifs ),
    T_MissionConverter("Pion ABC ReconnaitreAxe", "Pion ABC ReconnaitreAxe", eMission_Pion_ABC_ReconnaitreAxe ),
    T_MissionConverter("Pion ABC Soutenir", "Pion ABC Soutenir", eMission_Pion_ABC_Soutenir ),
    T_MissionConverter("Pion ABC Couvrir", "Pion ABC Couvrir", eMission_Pion_ABC_Couvrir ),
    T_MissionConverter("Pion ABC FlancGarder", "Pion ABC FlancGarder", eMission_Pion_ABC_FlancGarder ),
    T_MissionConverter("Pion ABC Reduire", "Pion ABC Reduire", eMission_Pion_ABC_Reduire ),
    T_MissionConverter("Pion ABC Appuyer", "Pion ABC Appuyer", eMission_Pion_ABC_Appuyer ),
    T_MissionConverter("Pion ABC Fixer", "Pion ABC Fixer", eMission_Pion_ABC_Fixer ),
    T_MissionConverter("Pion ABC RenseignerSur", "Pion ABC RenseignerSur", eMission_Pion_ABC_RenseignerSur ),
    T_MissionConverter("Pion ABC ControlerZone", "Pion ABC ControlerZone", eMission_Pion_ABC_ControlerZone ),
    T_MissionConverter("Pion ABC Surveiller", "Pion ABC Surveiller", eMission_Pion_ABC_Surveiller ),
    T_MissionConverter("Pion ABC Barrer", "Pion ABC Barrer", eMission_Pion_ABC_Barrer ),
    T_MissionConverter("Pion ABC Attaquer", "Pion ABC Attaquer", eMission_Pion_ABC_Attaquer ),
    T_MissionConverter("Pion ABC ReconnaitrePoint", "Pion ABC ReconnaitrePoint", eMission_Pion_ABC_ReconnaitrePoint ),
    T_MissionConverter("Pion ABC Eclairer", "Pion ABC Eclairer", eMission_Pion_ABC_Eclairer ),
    T_MissionConverter("Pion ABC Jalonner", "Pion ABC Jalonner", eMission_Pion_ABC_Jalonner ),
    T_MissionConverter("Pion ABC ContreAttaquer", "Pion ABC ContreAttaquer", eMission_Pion_ABC_ContreAttaquer ),
    T_MissionConverter("Pion ABC SemparerZone", "Pion ABC SemparerZone", eMission_Pion_ABC_SemparerZone ),
    T_MissionConverter("Pion ABC ReleverUnite", "Pion ABC ReleverUnite", eMission_Pion_ABC_ReleverUnite ),
    T_MissionConverter("Pion ABC ArmerPIA", "Pion ABC ArmerPIA", eMission_Pion_ABC_ArmerPIA ),
    T_MissionConverter("Pion ABC OuvrirItineraire", "Pion ABC OuvrirItineraire", eMission_Pion_ABC_OuvrirItineraire ),
    T_MissionConverter("Pion ABC Freiner", "Pion ABC Freiner", eMission_Pion_ABC_Freiner ),
    T_MissionConverter("Pion ABC EscorterUnConvoi", "Pion ABC EscorterUnConvoi", eMission_Pion_ABC_EscorterUnConvoi ),
    T_MissionConverter("Pion ABC ArmerPointDeControle", "Pion ABC ArmerPointDeControle", eMission_Pion_ABC_ArmerPointDeControle ),
    T_MissionConverter("Pion ABC OrganiserAccueilColonneRefugies", "Pion ABC OrganiserAccueilColonneRefugies", eMission_Pion_ABC_OrganiserAccueilColonneRefugies ),
    T_MissionConverter("Pion GEN RealiserFosseAC", "Pion GEN RealiserFosseAC", eMission_Pion_GEN_RealiserFosseAC ),
    T_MissionConverter("Pion GEN RealiserAbattisMine", "Pion GEN RealiserAbattisMine", eMission_Pion_GEN_RealiserAbattisMine ),
    T_MissionConverter("Pion GEN RealiserPointMine", "Pion GEN RealiserPointMine", eMission_Pion_GEN_RealiserPointMine ),
    T_MissionConverter("Pion GEN RealiserBarricade", "Pion GEN RealiserBarricade", eMission_Pion_GEN_RealiserBarricade ),
    T_MissionConverter("Pion GEN RealiserEboulement", "Pion GEN RealiserEboulement", eMission_Pion_GEN_RealiserEboulement ),
    T_MissionConverter("Pion GEN RealiserBouchonMine", "Pion GEN RealiserBouchonMine", eMission_Pion_GEN_RealiserBouchonMine ),
    T_MissionConverter("Pion GEN DetruireRoute", "Pion GEN DetruireRoute", eMission_Pion_GEN_DetruireRoute ),
    T_MissionConverter("Pion GEN DetruirePont", "Pion GEN DetruirePont", eMission_Pion_GEN_DetruirePont ),
    T_MissionConverter("Pion GEN SecuriserItineraire", "Pion GEN SecuriserItineraire", eMission_Pion_GEN_SecuriserItineraire ),
    T_MissionConverter("Pion GEN DegagerAbattisMine", "Pion GEN DegagerAbattisMine", eMission_Pion_GEN_DegagerAbattisMine ),
    T_MissionConverter("Pion GEN DegagerEboulement", "Pion GEN DegagerEboulement", eMission_Pion_GEN_DegagerEboulement ),
    T_MissionConverter("Pion GEN DegagerRues", "Pion GEN DegagerRues", eMission_Pion_GEN_DegagerRues ),
    T_MissionConverter("Pion GEN ComblerEntonnoir", "Pion GEN ComblerEntonnoir", eMission_Pion_GEN_ComblerEntonnoir ),
    T_MissionConverter("Pion GEN ComblerFosseAC", "Pion GEN ComblerFosseAC", eMission_Pion_GEN_ComblerFosseAC ),
    T_MissionConverter("Pion GEN CreerContournement", "Pion GEN CreerContournement", eMission_Pion_GEN_CreerContournement ),
    T_MissionConverter("Pion GEN RealiserZoneMineeLineaire", "Pion GEN RealiserZoneMineeLineaire", eMission_Pion_GEN_RealiserZoneMineeLineaire ),
    T_MissionConverter("Pion GEN OuvrirTrouee", "Pion GEN OuvrirTrouee", eMission_Pion_GEN_OuvrirTrouee ),
    T_MissionConverter("Pion GEN Renforcer", "Pion GEN Renforcer", eMission_Pion_GEN_Renforcer ),
    T_MissionConverter("Pion GEN FranchirEntonnoir", "Pion GEN FranchirEntonnoir", eMission_Pion_GEN_FranchirEntonnoir ),
    T_MissionConverter("Pion GEN FranchirFosseAC", "Pion GEN FranchirFosseAC", eMission_Pion_GEN_FranchirFosseAC ),
    T_MissionConverter("Pion GEN RealiserZoneMineeParDispersion", "Pion GEN RealiserZoneMineeParDispersion", eMission_Pion_GEN_RealiserZoneMineeParDispersion ),
    T_MissionConverter("Pion GEN RealiserPostesTir", "Pion GEN RealiserPostesTir", eMission_Pion_GEN_RealiserPostesTir ),
    T_MissionConverter("Pion GEN RealiserTravauxProtection", "Pion GEN RealiserTravauxProtection", eMission_Pion_GEN_RealiserTravauxProtection ),
    T_MissionConverter("Pion GEN RetablirItineraire", "Pion GEN RetablirItineraire", eMission_Pion_GEN_RetablirItineraire ),
    T_MissionConverter("Pion GEN EquiperExploiter", "Pion GEN EquiperExploiter", eMission_Pion_GEN_EquiperExploiter ),
    T_MissionConverter("Pion GEN ExecuterVariantement", "Pion GEN ExecuterVariantement", eMission_Pion_GEN_ExecuterVariantement ),
    T_MissionConverter("Pion GEN ReconnaitreSiteFranchissement", "Pion GEN ReconnaitreSiteFranchissement", eMission_Pion_GEN_ReconnaitreSiteFranchissement ),
    T_MissionConverter("Pion GEN ReconnaitreItineraire", "Pion GEN ReconnaitreItineraire", eMission_Pion_GEN_ReconnaitreItineraire ),
    T_MissionConverter("Pion GEN DeminerSiteFranchissement", "Pion GEN DeminerSiteFranchissement", eMission_Pion_GEN_DeminerSiteFranchissement ),
    T_MissionConverter("Pion GEN ReconnaitreZone", "Pion GEN ReconnaitreZone", eMission_Pion_GEN_ReconnaitreZone ),
    T_MissionConverter("Pion GEN CreerPlateForme", "Pion GEN CreerPlateForme", eMission_Pion_GEN_CreerPlateForme ),
    T_MissionConverter("Pion GEN CreerPiste", "Pion GEN CreerPiste", eMission_Pion_GEN_CreerPiste ),
    T_MissionConverter("Pion GEN CreerAirePoser", "Pion GEN CreerAirePoser", eMission_Pion_GEN_CreerAirePoser ),
    T_MissionConverter("Pion GEN NeutraliserEnginsExplosifs", "Pion GEN NeutraliserEnginsExplosifs", eMission_Pion_GEN_NeutraliserEnginsExplosifs ),
    T_MissionConverter("Pion GEN ActiverObstacle", "Pion GEN ActiverObstacle", eMission_Pion_GEN_ActiverObstacle ),
    T_MissionConverter("Pion GEN AmeliorerMobilite", "Pion GEN AmeliorerMobilite", eMission_Pion_GEN_AmeliorerMobilite ),
    T_MissionConverter("Pion GEN RealiserAireLogistique", "Pion GEN RealiserAireLogistique", eMission_Pion_GEN_RealiserAireLogistique ),
    T_MissionConverter("Pion GEN DepolluerZone", "Pion GEN DepolluerZone", eMission_Pion_GEN_DepolluerZone ),
    T_MissionConverter("Pion GEN AmenagerTerrainPoser", "Pion GEN AmenagerTerrainPoser", eMission_Pion_GEN_AmenagerTerrainPoser ),
    T_MissionConverter("Pion GEN RealiserPlateFormeDeploiement", "Pion GEN RealiserPlateFormeDeploiement", eMission_Pion_GEN_RealiserPlateFormeDeploiement ),
    T_MissionConverter("Pion GEN ReprendreMissionConstruction", "Pion GEN ReprendreMissionConstruction", eMission_Pion_GEN_ReprendreMissionConstruction ),
    T_MissionConverter("Pion GEN RealiserZonePoserHelicoptere", "Pion GEN RealiserZonePoserHelicoptere", eMission_Pion_GEN_RealiserZonePoserHelicoptere ),
    T_MissionConverter("Pion GEN AppuyerDebarquementTroupesGU", "Pion GEN AppuyerDebarquementTroupesGU", eMission_Pion_GEN_AppuyerDebarquementTroupesGU ),
    T_MissionConverter("Pion GEN RealiserCampPrisonniers", "Pion GEN RealiserCampPrisonniers", eMission_Pion_GEN_RealiserCampPrisonniers ),
    T_MissionConverter("Pion GEN RealiserCampRefugies", "Pion GEN RealiserCampRefugies", eMission_Pion_GEN_RealiserCampRefugies ),
    T_MissionConverter("Pion INF ReconnaitreAxe", "Pion INF ReconnaitreAxe", eMission_Pion_INF_ReconnaitreAxe ),
    T_MissionConverter("Pion INF Couvrir", "Pion INF Couvrir", eMission_Pion_INF_Couvrir ),
    T_MissionConverter("Pion INF Reduire", "Pion INF Reduire", eMission_Pion_INF_Reduire ),
    T_MissionConverter("Pion INF Appuyer", "Pion INF Appuyer", eMission_Pion_INF_Appuyer ),
    T_MissionConverter("Pion INF Fixer", "Pion INF Fixer", eMission_Pion_INF_Fixer ),
    T_MissionConverter("Pion INF ControlerSecteur", "Pion INF ControlerSecteur", eMission_Pion_INF_ControlerSecteur ),
    T_MissionConverter("Pion INF SurveillerSecteur", "Pion INF SurveillerSecteur", eMission_Pion_INF_SurveillerSecteur ),
    T_MissionConverter("Pion INF Barrer", "Pion INF Barrer", eMission_Pion_INF_Barrer ),
    T_MissionConverter("Pion INF ReconnaitrePoint", "Pion INF ReconnaitrePoint", eMission_Pion_INF_ReconnaitrePoint ),
    T_MissionConverter("Pion INF Eclairer", "Pion INF Eclairer", eMission_Pion_INF_Eclairer ),
    T_MissionConverter("Pion INF Interdire", "Pion INF Interdire", eMission_Pion_INF_Interdire ),
    T_MissionConverter("Pion INF Semparer", "Pion INF Semparer", eMission_Pion_INF_Semparer ),
    T_MissionConverter("Pion INF PrendrePreciserContact", "Pion INF PrendrePreciserContact", eMission_Pion_INF_PrendrePreciserContact ),
    T_MissionConverter("Pion INF Defendre", "Pion INF Defendre", eMission_Pion_INF_Defendre ),
    T_MissionConverter("Pion INF DetruireEmbuscade", "Pion INF DetruireEmbuscade", eMission_Pion_INF_DetruireEmbuscade ),
    T_MissionConverter("Pion INF ContreAttaquer", "Pion INF ContreAttaquer", eMission_Pion_INF_ContreAttaquer ),
    T_MissionConverter("Pion INF Freiner", "Pion INF Freiner", eMission_Pion_INF_Freiner ),
    T_MissionConverter("Pion INF FlancGarder", "Pion INF FlancGarder", eMission_Pion_INF_FlancGarder ),
    T_MissionConverter("Pion INF OrganiserUnCheckPoint", "Pion INF OrganiserUnCheckPoint", eMission_Pion_INF_OrganiserUnCheckPoint ),
    T_MissionConverter("Pion INF Harceler", "Pion INF Harceler", eMission_Pion_INF_Harceler ),
    T_MissionConverter("Pion INF DetruireParCoupDeMain", "Pion INF DetruireParCoupDeMain", eMission_Pion_INF_DetruireParCoupDeMain ),
    T_MissionConverter("Pion INF EscorterUnConvoi", "Pion INF EscorterUnConvoi", eMission_Pion_INF_EscorterUnConvoi ),
    T_MissionConverter("Pion INF RenseignerSur", "Pion INF RenseignerSur", eMission_Pion_INF_RenseignerSur ),
    T_MissionConverter("Pion INF Soutenir", "Pion INF Soutenir", eMission_Pion_INF_Soutenir ),
    T_MissionConverter("Pion INF Securiser", "Pion INF Securiser", eMission_Pion_INF_Securiser ),
    T_MissionConverter("Pion INF Recueillir", "Pion INF Recueillir", eMission_Pion_INF_Recueillir ),
    T_MissionConverter("Pion INF RepondreAAggression", "Pion INF RepondreAAggression", eMission_Pion_INF_RepondreAAggression ),
    T_MissionConverter("Pion LOG SeDeployer", "Pion LOG SeDeployer", eMission_Pion_LOG_SeDeployer ),
    T_MissionConverter("Pion LOG DistribuerMoyens", "Pion LOG DistribuerMoyens", eMission_Pion_LOG_DistribuerMoyens ),
    T_MissionConverter("Pion LOG TrierBlesses", "Pion LOG TrierBlesses", eMission_Pion_LOG_TrierBlesses ),
    T_MissionConverter("Pion LOG TraiterBlesses", "Pion LOG TraiterBlesses", eMission_Pion_LOG_TraiterBlesses ),
    T_MissionConverter("Pion LOG TrierEtTraiterBlesses", "Pion LOG TrierEtTraiterBlesses", eMission_Pion_LOG_TrierEtTraiterBlesses ),
    T_MissionConverter("Pion LOG SoignerBlesses", "Pion LOG SoignerBlesses", eMission_Pion_LOG_SoignerBlesses ),
    T_MissionConverter("Pion LOG PrendreEnCompteReactionsMentales", "Pion LOG PrendreEnCompteReactionsMentales", eMission_Pion_LOG_PrendreEnCompteReactionsMentales ),
    T_MissionConverter("Pion LOG DecontaminerBlesses", "Pion LOG DecontaminerBlesses", eMission_Pion_LOG_DecontaminerBlesses ),
    T_MissionConverter("Pion LOG Reparer", "Pion LOG Reparer", eMission_Pion_LOG_Reparer ),
    T_MissionConverter("Pion LOG Evacuer", "Pion LOG Evacuer", eMission_Pion_LOG_Evacuer ),
    T_MissionConverter("Pion LOG Convoyer", "Pion LOG Convoyer", eMission_Pion_LOG_Convoyer ),
    T_MissionConverter("Pion LOG DistribuerRessources", "Pion LOG DistribuerRessources", eMission_Pion_LOG_DistribuerRessources ),
    T_MissionConverter("Pion LOG ConstituerConvoi", "Pion LOG ConstituerConvoi", eMission_Pion_LOG_ConstituerConvoi ),
    T_MissionConverter("Pion LOG Livrer", "Pion LOG Livrer", eMission_Pion_LOG_Livrer ),
    T_MissionConverter("Pion LOG PreparerBascule", "Pion LOG PreparerBascule", eMission_Pion_LOG_PreparerBascule ),
    T_MissionConverter("Pion LOG AppuyerMouvement", "Pion LOG AppuyerMouvement", eMission_Pion_LOG_AppuyerMouvement ),
    T_MissionConverter("Pion LOG ReconnaitreItineraire", "Pion LOG ReconnaitreItineraire", eMission_Pion_LOG_ReconnaitreItineraire ),
    T_MissionConverter("Pion LOG TransporterUniteChars", "Pion LOG TransporterUniteChars", eMission_Pion_LOG_TransporterUniteChars ),
    T_MissionConverter("Pion LOG ReconnaitreZoneContaminee", "Pion LOG ReconnaitreZoneContaminee", eMission_Pion_LOG_ReconnaitreZoneContaminee ),
    T_MissionConverter("Pion LOG AppuyerMouvementDansZone", "Pion LOG AppuyerMouvementDansZone", eMission_Pion_LOG_AppuyerMouvementDansZone ),
    T_MissionConverter("Pion LOG MettreEnOeuvreZoneStationnement", "Pion LOG MettreEnOeuvreZoneStationnement", eMission_Pion_LOG_MettreEnOeuvreZoneStationnement ),
    T_MissionConverter("Pion LOG AppuyerFranchissementSurUnPoint", "Pion LOG AppuyerFranchissementSurUnPoint", eMission_Pion_LOG_AppuyerFranchissementSurUnPoint ),
    T_MissionConverter("Pion LOG BloquerZone", "Pion LOG BloquerZone", eMission_Pion_LOG_BloquerZone ),
    T_MissionConverter("Pion LOG ReconnaitreZoneDeDeploiement", "Pion LOG ReconnaitreZoneDeDeploiement", eMission_Pion_LOG_ReconnaitreZoneDeDeploiement ),
    T_MissionConverter("Pion LOG ArmerPIA", "Pion LOG ArmerPIA", eMission_Pion_LOG_ArmerPIA ),
    T_MissionConverter("Pion LOG Surveiller", "Pion LOG Surveiller", eMission_Pion_LOG_Surveiller ),
    T_MissionConverter("Pion Test Heliporter", "Pion Test Heliporter", eMission_Pion_Test_Heliporter ),
    T_MissionConverter("Pion Test MoveTo", "Pion Test MoveTo", eMission_Pion_Test_MoveTo ),
    T_MissionConverter("Pion Test CreateObject", "Pion Test CreateObject", eMission_Pion_Test_CreateObject ),
    T_MissionConverter("Pion Test DestroyObject", "Pion Test DestroyObject", eMission_Pion_Test_DestroyObject ),
    T_MissionConverter("Pion Test CreateBypass", "Pion Test CreateBypass", eMission_Pion_Test_CreateBypass ),
    T_MissionConverter("Pion Test Fire", "Pion Test Fire", eMission_Pion_Test_Fire ),
    T_MissionConverter("Pion Test ChangePosture", "Pion Test ChangePosture", eMission_Pion_Test_ChangePosture ),
    T_MissionConverter("Pion Test PathFind", "Pion Test PathFind", eMission_Pion_Test_PathFind ),
    T_MissionConverter("Pion Test FindPosition", "Pion Test FindPosition", eMission_Pion_Test_FindPosition ),
    T_MissionConverter("Pion Test Reinforce", "Pion Test Reinforce", eMission_Pion_Test_Reinforce ),
    T_MissionConverter("Pion PlastronEnnemi", "Pion PlastronEnnemi", eMission_Pion_PlastronEnnemi ),
    T_MissionConverter("Pion FaireMouvement", "Pion FaireMouvement", eMission_Pion_FaireMouvement ),
    T_MissionConverter("Pion Suivre", "Pion Suivre", eMission_Pion_Suivre ),
    T_MissionConverter("Pion SeFaireDecontaminer", "Pion SeFaireDecontaminer", eMission_Pion_SeFaireDecontaminer ),
    T_MissionConverter("Pion Franchir", "Pion Franchir", eMission_Pion_Franchir ),
    T_MissionConverter("Pion Decrocher", "Pion Decrocher", eMission_Pion_Decrocher ),
    T_MissionConverter("Pion Stationner", "Pion Stationner", eMission_Pion_Stationner ),
    T_MissionConverter("Pion SeFaireTransporter", "Pion SeFaireTransporter", eMission_Pion_SeFaireTransporter ),
    T_MissionConverter("Pion Generique", "Pion Generique", eMission_Pion_Generique ),
    T_MissionConverter("Pion MILICE Provoquer", "Pion MILICE Provoquer", eMission_Pion_MILICE_Provoquer ),
    T_MissionConverter("Pion MILICE PrendreEtTenir", "Pion MILICE PrendreEtTenir", eMission_Pion_MILICE_PrendreEtTenir ),
    T_MissionConverter("Pion MILICE DetruireEmbuscade", "Pion MILICE DetruireEmbuscade", eMission_Pion_MILICE_DetruireEmbuscade ),
    T_MissionConverter("Pion JOINT MARINE Transporter", "Pion JOINT MARINE Transporter", eMission_Pion_JOINT_MARINE_Transporter ),
    T_MissionConverter("Pion JOINT AIR EffectuerRaid", "Pion JOINT AIR EffectuerRaid", eMission_Pion_JOINT_AIR_EffectuerRaid ),
    T_MissionConverter("Pion NBC AnimerUnPlotDeDecontamination", "Pion NBC AnimerUnPlotDeDecontamination", eMission_Pion_NBC_AnimerUnPlotDeDecontamination ),
    T_MissionConverter("Pion NBC ReconnaitreItineraire", "Pion NBC ReconnaitreItineraire", eMission_Pion_NBC_ReconnaitreItineraire ),
    T_MissionConverter("Pion NBC ReconnaitreZone", "Pion NBC ReconnaitreZone", eMission_Pion_NBC_ReconnaitreZone ),
    T_MissionConverter("Pion NBC DecontaminerZone", "Pion NBC DecontaminerZone", eMission_Pion_NBC_DecontaminerZone ),
    T_MissionConverter("Pion NBC ReconnaitreUnSiteROTA", "Pion NBC ReconnaitreUnSiteROTA", eMission_Pion_NBC_ReconnaitreUnSiteROTA ),
    T_MissionConverter("Pion RENS ROHUM RenseignerSur", "Pion RENS ROHUM RenseignerSur", eMission_Pion_RENS_ROHUM_RenseignerSur ),
    T_MissionConverter("Pion RENS ROHUM SExfiltrer", "Pion RENS ROHUM SExfiltrer", eMission_Pion_RENS_ROHUM_SExfiltrer ),
    T_MissionConverter("Pion RENS ROHUM OrienterGuider", "Pion RENS ROHUM OrienterGuider", eMission_Pion_RENS_ROHUM_OrienterGuider ),
    T_MissionConverter("Pion RENS ROEM Appuyer", "Pion RENS ROEM Appuyer", eMission_Pion_RENS_ROEM_Appuyer ),
    T_MissionConverter("Pion RENS ROEM RenseignerSur", "Pion RENS ROEM RenseignerSur", eMission_Pion_RENS_ROEM_RenseignerSur ),
    T_MissionConverter("Pion RENS ROEM MettreEnOeuvre", "Pion RENS ROEM MettreEnOeuvre", eMission_Pion_RENS_ROEM_MettreEnOeuvre ),
    T_MissionConverter("Pion RENS RADINT RenseignerSur", "Pion RENS RADINT RenseignerSur", eMission_Pion_RENS_RADINT_RenseignerSur ),
    T_MissionConverter("Pion RENS RADINT MettreEnOeuvre", "Pion RENS RADINT MettreEnOeuvre", eMission_Pion_RENS_RADINT_MettreEnOeuvre ),
    T_MissionConverter("Pion RENS ROIM MettreEnOeuvre", "Pion RENS ROIM MettreEnOeuvre", eMission_Pion_RENS_ROIM_MettreEnOeuvre ),
    T_MissionConverter("Pion RENS ROIM SDTI RenseignerSur", "Pion RENS ROIM SDTI RenseignerSur", eMission_Pion_RENS_ROIM_SDTI_RenseignerSur ),
    T_MissionConverter("Pion RENS ROIM CL289 RenseignerSur", "Pion RENS ROIM CL289 RenseignerSur", eMission_Pion_RENS_ROIM_CL289_RenseignerSur ),
    T_MissionConverter("Pion TRANS EtablirGererLiaison", "Pion TRANS EtablirGererLiaison", eMission_Pion_TRANS_EtablirGererLiaison ),

    T_MissionConverter( ""           , ""                                           , (E_MissionID)-1  )
};