// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2006 Mathématiques Appliquées SA (MASA)
//
// *****************************************************************************

#include "gaming_pch.h"
#include "statusicons.h"

#define static 

#include "res/radars_on.xpm"
#include "res/skull.xpm"
#include "res/talkie_interdit.xpm"
#include "res/brouillage.xpm"
#include "res/gas.xpm"
#include "res/cadenas.xpm"
#include "res/nbc.xpm"
#include "res/medical.xpm"
#include "res/maintenance.xpm"
#include "res/supply.xpm"
#include "res/dotations.xpm"
#include "res/lendborrow.xpm"
#include "res/components.xpm"
#include "res/reinforced.xpm"
#include "res/reinforcing.xpm"
#include "res/morale_fanatic.xpm"
#include "res/morale_good.xpm"
#include "res/morale_medium.xpm"
#include "res/morale_bad.xpm"
#include "res/experience_rookie.xpm"
#include "res/experience_experienced.xpm"
#include "res/experience_veteran.xpm"
#include "res/tiredness_normal.xpm"
#include "res/tiredness_tired.xpm"
#include "res/tiredness_exhausted.xpm"
#include "res/stance_move.xpm"
#include "res/stance_discreet.xpm"
#include "res/stance_stop.xpm"
#include "res/stance_reflex.xpm"
#include "res/stance_posted.xpm"
#include "res/stance_equipped.xpm"
#include "res/stance_engineered.xpm"
#include "res/stance_arrow.xpm"
#include "res/parent.xpm"
#include "res/mission.xpm"
#include "res/mission_title.xpm"
#include "res/parameter2.xpm"
#include "res/checkpoint.xpm"
#include "res/checkpoint1.xpm"
#include "res/checkpoint2.xpm"
#include "res/checkpoint3.xpm"
#include "res/activated.xpm"
#include "res/not_activated.xpm"
#include "res/replayer.xpm"
#include "res/timer.xpm"
#include "res/aaa_function_copy.xpm"
#include "res/aaa_function_edit.xpm"
#include "res/aaa_function_delete.xpm"
#include "res/aaa_function_new.xpm"
#include "res/aaa_broken.xpm"
#include "res/aaa_pending.xpm"
#include "res/aaa_valid.xpm"
#include "res/aaa_link.xpm"
#include "res/aaa_move.xpm"