// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2004 Mathématiques Appliquées SA (MASA)
//
// *****************************************************************************
//
// $Created: $
// $Archive: /MVW_v10/Build/SDK/AGR/src/AGR_ADN2_Tr_Gen_Skeleton.cpp $
// $Author: Ape $
// $Modtime: 17/02/05 17:22 $
// $Revision: 1 $
// $Workfile: AGR_ADN2_Tr_Gen_Skeleton.cpp $
//
// *****************************************************************************

#include "ADN_pch.h"
#include "ADN_Tr.h"

ADN_Tr::T_ConverterSMission ADN_Tr::smissionConverter_[] =
{
    T_ConverterSMission("Automate ABC ArmerPointDeControle", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC ArmerPointDeControle"), eSMission_Automate_ABC_ArmerPointDeControle ),
    T_ConverterSMission("Automate ABC OrganiserAccueilColonneRefugies", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC OrganiserAccueilColonneRefugies"), eSMission_Automate_ABC_OrganiserAccueilColonneRefugies ),
    T_ConverterSMission("Automate ABC ProtegerPC", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC ProtegerPC"), eSMission_Automate_ABC_ProtegerPC ),
    T_ConverterSMission("Automate ABC Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Appuyer"), eSMission_Automate_ABC_Appuyer ),
    T_ConverterSMission("Automate ABC Attaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Attaquer"), eSMission_Automate_ABC_Attaquer ),
    T_ConverterSMission("Automate ABC ContreAttaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC ContreAttaquer"), eSMission_Automate_ABC_ContreAttaquer ),
    T_ConverterSMission("Automate ABC Controler", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Controler"), eSMission_Automate_ABC_Controler ),
    T_ConverterSMission("Automate ABC Couvrir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Couvrir"), eSMission_Automate_ABC_Couvrir ),
    T_ConverterSMission("Automate ABC DonnerCoupArret", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC DonnerCoupArret"), eSMission_Automate_ABC_DonnerCoupArret ),
    T_ConverterSMission("Automate ABC Eclairer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Eclairer"), eSMission_Automate_ABC_Eclairer ),
    T_ConverterSMission("Automate ABC EffectuerRaid", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC EffectuerRaid"), eSMission_Automate_ABC_EffectuerRaid ),
    T_ConverterSMission("Automate ABC Interdire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Interdire"), eSMission_Automate_ABC_Interdire ),
    T_ConverterSMission("Automate ABC Jalonner", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Jalonner"), eSMission_Automate_ABC_Jalonner ),
    T_ConverterSMission("Automate ABC PrendrePreciserContact", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC PrendrePreciserContact"), eSMission_Automate_ABC_PrendrePreciserContact ),
    T_ConverterSMission("Automate ABC Reconnaitre", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Reconnaitre"), eSMission_Automate_ABC_Reconnaitre ),
    T_ConverterSMission("Automate ABC ReconnaitrePoint", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC ReconnaitrePoint"), eSMission_Automate_ABC_ReconnaitrePoint ),
    T_ConverterSMission("Automate ABC Reduire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Reduire"), eSMission_Automate_ABC_Reduire ),
    T_ConverterSMission("Automate ABC ReleverEnDepassant", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC ReleverEnDepassant"), eSMission_Automate_ABC_ReleverEnDepassant ),
    T_ConverterSMission("Automate ABC Semparer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Semparer"), eSMission_Automate_ABC_Semparer ),
    T_ConverterSMission("Automate ABC Tenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Tenir"), eSMission_Automate_ABC_Tenir ),
    T_ConverterSMission("Automate ABC Soutenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Soutenir"), eSMission_Automate_ABC_Soutenir ),
    T_ConverterSMission("Automate ABC Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Surveiller"), eSMission_Automate_ABC_Surveiller ),
    T_ConverterSMission("Automate ABC FlancGarder", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC FlancGarder"), eSMission_Automate_ABC_FlancGarder ),
    T_ConverterSMission("Automate ABC RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC RenseignerSur"), eSMission_Automate_ABC_RenseignerSur ),
    T_ConverterSMission("Automate ABC Fixer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Fixer"), eSMission_Automate_ABC_Fixer ),
    T_ConverterSMission("Automate ABC Freiner", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC Freiner"), eSMission_Automate_ABC_Freiner ),
    T_ConverterSMission("Automate ABC SurveillerItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC SurveillerItineraire"), eSMission_Automate_ABC_SurveillerItineraire ),
    T_ConverterSMission("Automate ABC RenseignerSurUnAxe", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC RenseignerSurUnAxe"), eSMission_Automate_ABC_RenseignerSurUnAxe ),
    T_ConverterSMission("Automate ABC RecueillirUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC RecueillirUnite"), eSMission_Automate_ABC_RecueillirUnite ),
    T_ConverterSMission("Automate ABC EscorterUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC EscorterUnite"), eSMission_Automate_ABC_EscorterUnite ),
    T_ConverterSMission("Automate ABC EscorterUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC EscorterUnites"), eSMission_Automate_ABC_EscorterUnites ),
    T_ConverterSMission("Automate ABC AppuyerSurPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ABC AppuyerSurPosition"), eSMission_Automate_ABC_AppuyerSurPosition ),
    T_ConverterSMission("Pion ALAT EvacuationSanitaire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT EvacuationSanitaire"), eSMission_Pion_ALAT_EvacuationSanitaire ),
    T_ConverterSMission("Pion ALAT ReconnaitreDansLaProfondeur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT ReconnaitreDansLaProfondeur"), eSMission_Pion_ALAT_ReconnaitreDansLaProfondeur ),
    T_ConverterSMission("Pion ALAT ReconnaitreContourEnnemi", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT ReconnaitreContourEnnemi"), eSMission_Pion_ALAT_ReconnaitreContourEnnemi ),
    T_ConverterSMission("Pion ALAT DetruireNeutraliserDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT DetruireNeutraliserDansZone"), eSMission_Pion_ALAT_DetruireNeutraliserDansZone ),
    T_ConverterSMission("Pion ALAT DetruireAeromobile", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT DetruireAeromobile"), eSMission_Pion_ALAT_DetruireAeromobile ),
    T_ConverterSMission("Pion ALAT Freiner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Freiner"), eSMission_Pion_ALAT_Freiner ),
    T_ConverterSMission("Pion ALAT Jalonner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Jalonner"), eSMission_Pion_ALAT_Jalonner ),
    T_ConverterSMission("Pion ALAT Escorter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Escorter"), eSMission_Pion_ALAT_Escorter ),
    T_ConverterSMission("Pion ALAT Heliporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Heliporter"), eSMission_Pion_ALAT_Heliporter ),
    T_ConverterSMission("Pion ALAT HeliporterHelitransporterPlotRavitaillement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT HeliporterHelitransporterPlotRavitaillement"), eSMission_Pion_ALAT_HeliporterHelitransporterPlotRavitaillement ),
    T_ConverterSMission("Pion ALAT Helitransporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Helitransporter"), eSMission_Pion_ALAT_Helitransporter ),
    T_ConverterSMission("Pion ALAT EffectuerRechercheEtSauvetage", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT EffectuerRechercheEtSauvetage"), eSMission_Pion_ALAT_EffectuerRechercheEtSauvetage ),
    T_ConverterSMission("Pion ALAT IMEX", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT IMEX"), eSMission_Pion_ALAT_IMEX ),
    T_ConverterSMission("Pion ALAT Eclairer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Eclairer"), eSMission_Pion_ALAT_Eclairer ),
    T_ConverterSMission("Pion ALAT Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Surveiller"), eSMission_Pion_ALAT_Surveiller ),
    T_ConverterSMission("Pion ALAT AppuyerDirectAuContact", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT AppuyerDirectAuContact"), eSMission_Pion_ALAT_AppuyerDirectAuContact ),
    T_ConverterSMission("Pion ALAT Couvrir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Couvrir"), eSMission_Pion_ALAT_Couvrir ),
    T_ConverterSMission("Pion ALAT Attaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ALAT Attaquer"), eSMission_Pion_ALAT_Attaquer ),
    T_ConverterSMission("Automate ALAT Heliporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Heliporter"), eSMission_Automate_ALAT_Heliporter ),
    T_ConverterSMission("Automate ALAT Jalonner", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Jalonner"), eSMission_Automate_ALAT_Jalonner ),
    T_ConverterSMission("Automate ALAT Helitransporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Helitransporter"), eSMission_Automate_ALAT_Helitransporter ),
    T_ConverterSMission("Automate ALAT ExtrairePersonnel", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT ExtrairePersonnel"), eSMission_Automate_ALAT_ExtrairePersonnel ),
    T_ConverterSMission("Automate ALAT Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Appuyer"), eSMission_Automate_ALAT_Appuyer ),
    T_ConverterSMission("Automate ALAT Couvrir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Couvrir"), eSMission_Automate_ALAT_Couvrir ),
    T_ConverterSMission("Automate ALAT Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Surveiller"), eSMission_Automate_ALAT_Surveiller ),
    T_ConverterSMission("Automate ALAT Reconnaitre", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Reconnaitre"), eSMission_Automate_ALAT_Reconnaitre ),
    T_ConverterSMission("Automate ALAT Freiner", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Freiner"), eSMission_Automate_ALAT_Freiner ),
    T_ConverterSMission("Automate ALAT Escorter", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Escorter"), eSMission_Automate_ALAT_Escorter ),
    T_ConverterSMission("Automate ALAT Attaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT Attaquer"), eSMission_Automate_ALAT_Attaquer ),
    T_ConverterSMission("Automate ALAT RecueillirFormationAeromobile", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT RecueillirFormationAeromobile"), eSMission_Automate_ALAT_RecueillirFormationAeromobile ),
    T_ConverterSMission("Automate ALAT AttaquerFormationAeromobile", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT AttaquerFormationAeromobile"), eSMission_Automate_ALAT_AttaquerFormationAeromobile ),
    T_ConverterSMission("Automate ALAT DonnerCoupArret", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT DonnerCoupArret"), eSMission_Automate_ALAT_DonnerCoupArret ),
    T_ConverterSMission("Automate ALAT DetruireNeutraliserDansProfondeur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT DetruireNeutraliserDansProfondeur"), eSMission_Automate_ALAT_DetruireNeutraliserDansProfondeur ),
    T_ConverterSMission("Automate ALAT DetruireNeutraliserDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT DetruireNeutraliserDansZone"), eSMission_Automate_ALAT_DetruireNeutraliserDansZone ),
    T_ConverterSMission("Automate ALAT EffectuerRechercheEtSauvetage", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ALAT EffectuerRechercheEtSauvetage"), eSMission_Automate_ALAT_EffectuerRechercheEtSauvetage ),
    T_ConverterSMission("Automate ASA DefendreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA DefendreZone"), eSMission_Automate_ASA_DefendreZone ),
    T_ConverterSMission("Automate ASA DefendreSite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA DefendreSite"), eSMission_Automate_ASA_DefendreSite ),
    T_ConverterSMission("Automate ASA Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA Surveiller"), eSMission_Automate_ASA_Surveiller ),
    T_ConverterSMission("Automate ASA DefendreItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA DefendreItineraire"), eSMission_Automate_ASA_DefendreItineraire ),
    T_ConverterSMission("Automate ASA MISTRAL DefendreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA MISTRAL DefendreZone"), eSMission_Automate_ASA_MISTRAL_DefendreZone ),
    T_ConverterSMission("Automate ASA MISTRAL DefendreSite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA MISTRAL DefendreSite"), eSMission_Automate_ASA_MISTRAL_DefendreSite ),
    T_ConverterSMission("Automate ASA MISTRAL Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA MISTRAL Surveiller"), eSMission_Automate_ASA_MISTRAL_Surveiller ),
    T_ConverterSMission("Automate ASA HAWK DefendreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA HAWK DefendreZone"), eSMission_Automate_ASA_HAWK_DefendreZone ),
    T_ConverterSMission("Automate ASA HAWK DefendreSite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA HAWK DefendreSite"), eSMission_Automate_ASA_HAWK_DefendreSite ),
    T_ConverterSMission("Automate ASA HAWK Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA HAWK Surveiller"), eSMission_Automate_ASA_HAWK_Surveiller ),
    T_ConverterSMission("Automate ASA DefendreUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASA DefendreUnites"), eSMission_Automate_ASA_DefendreUnites ),
    T_ConverterSMission("Automate ASS SeDeployer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASS SeDeployer"), eSMission_Automate_ASS_SeDeployer ),
    T_ConverterSMission("Automate ASS ReconnaitreZonesDeploiement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASS ReconnaitreZonesDeploiement"), eSMission_Automate_ASS_ReconnaitreZonesDeploiement ),
    T_ConverterSMission("Automate ASS AcquerirObjectifs", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ASS AcquerirObjectifs"), eSMission_Automate_ASS_AcquerirObjectifs ),
    T_ConverterSMission("Automate GEN SeDeployer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN SeDeployer"), eSMission_Automate_GEN_SeDeployer ),
    T_ConverterSMission("Automate GEN FaireFranchir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN FaireFranchir"), eSMission_Automate_GEN_FaireFranchir ),
    T_ConverterSMission("Automate GEN RealiserSystemeObstacles", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RealiserSystemeObstacles"), eSMission_Automate_GEN_RealiserSystemeObstacles ),
    T_ConverterSMission("Automate GEN FranchirDeViveForce", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN FranchirDeViveForce"), eSMission_Automate_GEN_FranchirDeViveForce ),
    T_ConverterSMission("Automate GEN RetablirItineraires", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RetablirItineraires"), eSMission_Automate_GEN_RetablirItineraires ),
    T_ConverterSMission("Automate GEN AmenagerAireStationnement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN AmenagerAireStationnement"), eSMission_Automate_GEN_AmenagerAireStationnement ),
    T_ConverterSMission("Automate GEN AmenagerTerrainPoserSommaire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN AmenagerTerrainPoserSommaire"), eSMission_Automate_GEN_AmenagerTerrainPoserSommaire ),
    T_ConverterSMission("Automate GEN RealiserZonePoser", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RealiserZonePoser"), eSMission_Automate_GEN_RealiserZonePoser ),
    T_ConverterSMission("Automate GEN ReconnaitreZoneDeploiement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN ReconnaitreZoneDeploiement"), eSMission_Automate_GEN_ReconnaitreZoneDeploiement ),
    T_ConverterSMission("Automate GEN RealiserCampPrisonniers", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RealiserCampPrisonniers"), eSMission_Automate_GEN_RealiserCampPrisonniers ),
    T_ConverterSMission("Automate GEN RealiserCampRefugies", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RealiserCampRefugies"), eSMission_Automate_GEN_RealiserCampRefugies ),
    T_ConverterSMission("Automate GEN RealiserPlatesformesSommairesDeDeploiementInitial", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RealiserPlatesformesSommairesDeDeploiementInitial"), eSMission_Automate_GEN_RealiserPlatesformesSommairesDeDeploiementInitial ),
    T_ConverterSMission("Automate GEN RealiserTravauxSommairesAuProfitPopulation", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN RealiserTravauxSommairesAuProfitPopulation"), eSMission_Automate_GEN_RealiserTravauxSommairesAuProfitPopulation ),
    T_ConverterSMission("Automate GEN AppuyerDebarquementTroupes", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN AppuyerDebarquementTroupes"), eSMission_Automate_GEN_AppuyerDebarquementTroupes ),
    T_ConverterSMission("Automate GEN OuvrirAxesProgression", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate GEN OuvrirAxesProgression"), eSMission_Automate_GEN_OuvrirAxesProgression ),
    T_ConverterSMission("Automate INF AttaquerSouplesse", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF AttaquerSouplesse"), eSMission_Automate_INF_AttaquerSouplesse ),
    T_ConverterSMission("Automate INF Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Appuyer"), eSMission_Automate_INF_Appuyer ),
    T_ConverterSMission("Automate INF Controler", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Controler"), eSMission_Automate_INF_Controler ),
    T_ConverterSMission("Automate INF Couvrir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Couvrir"), eSMission_Automate_INF_Couvrir ),
    T_ConverterSMission("Automate INF DonnerCoupArret", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF DonnerCoupArret"), eSMission_Automate_INF_DonnerCoupArret ),
    T_ConverterSMission("Automate INF Eclairer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Eclairer"), eSMission_Automate_INF_Eclairer ),
    T_ConverterSMission("Automate INF FlancGarder", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF FlancGarder"), eSMission_Automate_INF_FlancGarder ),
    T_ConverterSMission("Automate INF Freiner", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Freiner"), eSMission_Automate_INF_Freiner ),
    T_ConverterSMission("Automate INF Harceler", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Harceler"), eSMission_Automate_INF_Harceler ),
    T_ConverterSMission("Automate INF Interdire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Interdire"), eSMission_Automate_INF_Interdire ),
    T_ConverterSMission("Automate INF MenerDefenseUsure", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF MenerDefenseUsure"), eSMission_Automate_INF_MenerDefenseUsure ),
    T_ConverterSMission("Automate INF PrendrePreciserMaintenirContact", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF PrendrePreciserMaintenirContact"), eSMission_Automate_INF_PrendrePreciserMaintenirContact ),
    T_ConverterSMission("Automate INF ReconnaissanceOffensive", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF ReconnaissanceOffensive"), eSMission_Automate_INF_ReconnaissanceOffensive ),
    T_ConverterSMission("Automate INF RecueillirUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF RecueillirUnite"), eSMission_Automate_INF_RecueillirUnite ),
    T_ConverterSMission("Automate INF Reduire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Reduire"), eSMission_Automate_INF_Reduire ),
    T_ConverterSMission("Automate INF Relever", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Relever"), eSMission_Automate_INF_Relever ),
    T_ConverterSMission("Automate INF RompreContact", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF RompreContact"), eSMission_Automate_INF_RompreContact ),
    T_ConverterSMission("Automate INF Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Surveiller"), eSMission_Automate_INF_Surveiller ),
    T_ConverterSMission("Automate INF Semparer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Semparer"), eSMission_Automate_INF_Semparer ),
    T_ConverterSMission("Automate INF Fixer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Fixer"), eSMission_Automate_INF_Fixer ),
    T_ConverterSMission("Automate INF AttaquerEnTerrainDifficile", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF AttaquerEnTerrainDifficile"), eSMission_Automate_INF_AttaquerEnTerrainDifficile ),
    T_ConverterSMission("Automate INF BarrerDirection", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF BarrerDirection"), eSMission_Automate_INF_BarrerDirection ),
    T_ConverterSMission("Automate INF DefendreFerme", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF DefendreFerme"), eSMission_Automate_INF_DefendreFerme ),
    T_ConverterSMission("Automate INF Tenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Tenir"), eSMission_Automate_INF_Tenir ),
    T_ConverterSMission("Automate INF AppuyerUnFreinage", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF AppuyerUnFreinage"), eSMission_Automate_INF_AppuyerUnFreinage ),
    T_ConverterSMission("Automate INF AppuyerUneAttaque", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF AppuyerUneAttaque"), eSMission_Automate_INF_AppuyerUneAttaque ),
    T_ConverterSMission("Automate INF Soutenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF Soutenir"), eSMission_Automate_INF_Soutenir ),
    T_ConverterSMission("Automate INF EscorterUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF EscorterUnite"), eSMission_Automate_INF_EscorterUnite ),
    T_ConverterSMission("Automate INF EscorterUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF EscorterUnites"), eSMission_Automate_INF_EscorterUnites ),
    T_ConverterSMission("Automate INF AppuyerSurPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate INF AppuyerSurPosition"), eSMission_Automate_INF_AppuyerSurPosition ),
    T_ConverterSMission("Automate LOG SeDeployer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG SeDeployer"), eSMission_Automate_LOG_SeDeployer ),
    T_ConverterSMission("Automate LOG AppuyerMouvement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG AppuyerMouvement"), eSMission_Automate_LOG_AppuyerMouvement ),
    T_ConverterSMission("Automate LOG ReconnaitreItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG ReconnaitreItineraire"), eSMission_Automate_LOG_ReconnaitreItineraire ),
    T_ConverterSMission("Automate LOG Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG Surveiller"), eSMission_Automate_LOG_Surveiller ),
    T_ConverterSMission("Automate LOG TransporterUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG TransporterUnites"), eSMission_Automate_LOG_TransporterUnites ),
    T_ConverterSMission("Automate LOG AppuyerMouvementDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG AppuyerMouvementDansZone"), eSMission_Automate_LOG_AppuyerMouvementDansZone ),
    T_ConverterSMission("Automate LOG MettreEnOeuvreZoneStationnement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG MettreEnOeuvreZoneStationnement"), eSMission_Automate_LOG_MettreEnOeuvreZoneStationnement ),
    T_ConverterSMission("Automate LOG AppuyerFranchissementDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG AppuyerFranchissementDansZone"), eSMission_Automate_LOG_AppuyerFranchissementDansZone ),
    T_ConverterSMission("Automate LOG BloquerZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG BloquerZone"), eSMission_Automate_LOG_BloquerZone ),
    T_ConverterSMission("Automate LOG ReconnaitreZoneContaminee", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG ReconnaitreZoneContaminee"), eSMission_Automate_LOG_ReconnaitreZoneContaminee ),
    T_ConverterSMission("Automate LOG ReconnaitreZoneDeDeploiement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG ReconnaitreZoneDeDeploiement"), eSMission_Automate_LOG_ReconnaitreZoneDeDeploiement ),
    T_ConverterSMission("Automate LOG ArmerPIAs", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate LOG ArmerPIAs"), eSMission_Automate_LOG_ArmerPIAs ),
    T_ConverterSMission("Automate Test MoveTo", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate Test MoveTo"), eSMission_Automate_Test_MoveTo ),
    T_ConverterSMission("Automate Decrocher", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate Decrocher"), eSMission_Automate_Decrocher ),
    T_ConverterSMission("Automate ReleverSurPlace", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate ReleverSurPlace"), eSMission_Automate_ReleverSurPlace ),
    T_ConverterSMission("Automate FaireMouvement", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate FaireMouvement"), eSMission_Automate_FaireMouvement ),
    T_ConverterSMission("Automate SeFaireDecontaminer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate SeFaireDecontaminer"), eSMission_Automate_SeFaireDecontaminer ),
    T_ConverterSMission("Automate Franchir", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate Franchir"), eSMission_Automate_Franchir ),
    T_ConverterSMission("Automate Stationner", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate Stationner"), eSMission_Automate_Stationner ),
    T_ConverterSMission("Automate SeFaireTransporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate SeFaireTransporter"), eSMission_Automate_SeFaireTransporter ),
    T_ConverterSMission("Automate SeRecompleter", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate SeRecompleter"), eSMission_Automate_SeRecompleter ),
    T_ConverterSMission("Automate SeRendre", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate SeRendre"), eSMission_Automate_SeRendre ),
    T_ConverterSMission("Automate FaireMouvementVersCampRefugies", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate FaireMouvementVersCampRefugies"), eSMission_Automate_FaireMouvementVersCampRefugies ),
    T_ConverterSMission("Automate Generique", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate Generique"), eSMission_Automate_Generique ),
    T_ConverterSMission("Automate NBC ReconnaitreUnAxe", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate NBC ReconnaitreUnAxe"), eSMission_Automate_NBC_ReconnaitreUnAxe ),
    T_ConverterSMission("Automate NBC ReconnaitreUneZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate NBC ReconnaitreUneZone"), eSMission_Automate_NBC_ReconnaitreUneZone ),
    T_ConverterSMission("Automate NBC ArmerUnSiteDeDecontamination", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate NBC ArmerUnSiteDeDecontamination"), eSMission_Automate_NBC_ArmerUnSiteDeDecontamination ),
    T_ConverterSMission("Automate NBC DecontaminerUneZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate NBC DecontaminerUneZone"), eSMission_Automate_NBC_DecontaminerUneZone ),
    T_ConverterSMission("Automate NBC ReconnaitreDesSitesROTA", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate NBC ReconnaitreDesSitesROTA"), eSMission_Automate_NBC_ReconnaitreDesSitesROTA ),
    T_ConverterSMission("Automate RENS ROHUM RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROHUM RenseignerSur"), eSMission_Automate_RENS_ROHUM_RenseignerSur ),
    T_ConverterSMission("Automate RENS ROHUM OrienterGuider", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROHUM OrienterGuider"), eSMission_Automate_RENS_ROHUM_OrienterGuider ),
    T_ConverterSMission("Automate RENS ROHUM SExfiltrer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROHUM SExfiltrer"), eSMission_Automate_RENS_ROHUM_SExfiltrer ),
    T_ConverterSMission("Automate RENS ROIM CL289 RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROIM CL289 RenseignerSur"), eSMission_Automate_RENS_ROIM_CL289_RenseignerSur ),
    T_ConverterSMission("Automate RENS ROIM SDTI RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROIM SDTI RenseignerSur"), eSMission_Automate_RENS_ROIM_SDTI_RenseignerSur ),
    T_ConverterSMission("Automate RENS ROEM Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROEM Appuyer"), eSMission_Automate_RENS_ROEM_Appuyer ),
    T_ConverterSMission("Automate RENS ROEM RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS ROEM RenseignerSur"), eSMission_Automate_RENS_ROEM_RenseignerSur ),
    T_ConverterSMission("Automate RENS RADINT RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate RENS RADINT RenseignerSur"), eSMission_Automate_RENS_RADINT_RenseignerSur ),
    T_ConverterSMission("Automate TRANS Commander", QT_TRANSLATE_NOOP( "ADN_Enums", "Automate TRANS Commander"), eSMission_Automate_TRANS_Commander ),
    T_ConverterSMission("Pion ASA DefendreSite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA DefendreSite"), eSMission_Pion_ASA_DefendreSite ),
    T_ConverterSMission("Pion ASA DefendreSiteAPartirPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA DefendreSiteAPartirPosition"), eSMission_Pion_ASA_DefendreSiteAPartirPosition ),
    T_ConverterSMission("Pion ASA DefendreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA DefendreZone"), eSMission_Pion_ASA_DefendreZone ),
    T_ConverterSMission("Pion ASA DefendreZoneAPartirPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA DefendreZoneAPartirPosition"), eSMission_Pion_ASA_DefendreZoneAPartirPosition ),
    T_ConverterSMission("Pion ASA Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA Surveiller"), eSMission_Pion_ASA_Surveiller ),
    T_ConverterSMission("Pion ASA DefendreUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA DefendreUnites"), eSMission_Pion_ASA_DefendreUnites ),
    T_ConverterSMission("Pion ASA MISTRAL DefendreSite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA MISTRAL DefendreSite"), eSMission_Pion_ASA_MISTRAL_DefendreSite ),
    T_ConverterSMission("Pion ASA MISTRAL DefendreSiteAPartirPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA MISTRAL DefendreSiteAPartirPosition"), eSMission_Pion_ASA_MISTRAL_DefendreSiteAPartirPosition ),
    T_ConverterSMission("Pion ASA MISTRAL DefendreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA MISTRAL DefendreZone"), eSMission_Pion_ASA_MISTRAL_DefendreZone ),
    T_ConverterSMission("Pion ASA MISTRAL DefendreZoneAPartirPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA MISTRAL DefendreZoneAPartirPosition"), eSMission_Pion_ASA_MISTRAL_DefendreZoneAPartirPosition ),
    T_ConverterSMission("Pion ASA MISTRAL Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASA MISTRAL Surveiller"), eSMission_Pion_ASA_MISTRAL_Surveiller ),
    T_ConverterSMission("Pion ASS AssurerMiseEnOeuvre", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS AssurerMiseEnOeuvre"), eSMission_Pion_ASS_AssurerMiseEnOeuvre ),
    T_ConverterSMission("Pion ASS AssurerMiseEnOeuvreSurPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS AssurerMiseEnOeuvreSurPosition"), eSMission_Pion_ASS_AssurerMiseEnOeuvreSurPosition ),
    T_ConverterSMission("Pion ASS ReconnaitreZoneDeploiement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS ReconnaitreZoneDeploiement"), eSMission_Pion_ASS_ReconnaitreZoneDeploiement ),
    T_ConverterSMission("Pion ASS AcquerirLanceursEni", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS AcquerirLanceursEni"), eSMission_Pion_ASS_AcquerirLanceursEni ),
    T_ConverterSMission("Pion ASS EO AcquerirObjectifs", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS EO AcquerirObjectifs"), eSMission_Pion_ASS_EO_AcquerirObjectifs ),
    T_ConverterSMission("Pion ASS EOP AcquerirObjectifs", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS EOP AcquerirObjectifs"), eSMission_Pion_ASS_EOP_AcquerirObjectifs ),
    T_ConverterSMission("Pion ASS RATAC AcquerirObjectifs", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASS RATAC AcquerirObjectifs"), eSMission_Pion_ASS_RATAC_AcquerirObjectifs ),
    T_ConverterSMission("Pion ABC ReconnaitreAxe", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ReconnaitreAxe"), eSMission_Pion_ABC_ReconnaitreAxe ),
    T_ConverterSMission("Pion ABC Soutenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Soutenir"), eSMission_Pion_ABC_Soutenir ),
    T_ConverterSMission("Pion ABC Couvrir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Couvrir"), eSMission_Pion_ABC_Couvrir ),
    T_ConverterSMission("Pion ABC FlancGarder", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC FlancGarder"), eSMission_Pion_ABC_FlancGarder ),
    T_ConverterSMission("Pion ABC Reduire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Reduire"), eSMission_Pion_ABC_Reduire ),
    T_ConverterSMission("Pion ABC Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Appuyer"), eSMission_Pion_ABC_Appuyer ),
    T_ConverterSMission("Pion ABC Fixer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Fixer"), eSMission_Pion_ABC_Fixer ),
    T_ConverterSMission("Pion ABC RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC RenseignerSur"), eSMission_Pion_ABC_RenseignerSur ),
    T_ConverterSMission("Pion ABC ControlerZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ControlerZone"), eSMission_Pion_ABC_ControlerZone ),
    T_ConverterSMission("Pion ABC Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Surveiller"), eSMission_Pion_ABC_Surveiller ),
    T_ConverterSMission("Pion ABC Barrer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Barrer"), eSMission_Pion_ABC_Barrer ),
    T_ConverterSMission("Pion ABC Attaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Attaquer"), eSMission_Pion_ABC_Attaquer ),
    T_ConverterSMission("Pion ABC ReconnaitrePoint", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ReconnaitrePoint"), eSMission_Pion_ABC_ReconnaitrePoint ),
    T_ConverterSMission("Pion ABC Eclairer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Eclairer"), eSMission_Pion_ABC_Eclairer ),
    T_ConverterSMission("Pion ABC Jalonner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Jalonner"), eSMission_Pion_ABC_Jalonner ),
    T_ConverterSMission("Pion ABC ContreAttaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ContreAttaquer"), eSMission_Pion_ABC_ContreAttaquer ),
    T_ConverterSMission("Pion ABC SemparerZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC SemparerZone"), eSMission_Pion_ABC_SemparerZone ),
    T_ConverterSMission("Pion ABC ReleverUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ReleverUnite"), eSMission_Pion_ABC_ReleverUnite ),
    T_ConverterSMission("Pion ABC ArmerPIA", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ArmerPIA"), eSMission_Pion_ABC_ArmerPIA ),
    T_ConverterSMission("Pion ABC OuvrirItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC OuvrirItineraire"), eSMission_Pion_ABC_OuvrirItineraire ),
    T_ConverterSMission("Pion ABC Freiner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC Freiner"), eSMission_Pion_ABC_Freiner ),
    T_ConverterSMission("Pion ABC EscorterUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC EscorterUnite"), eSMission_Pion_ABC_EscorterUnite ),
    T_ConverterSMission("Pion ABC EscorterUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC EscorterUnites"), eSMission_Pion_ABC_EscorterUnites ),
    T_ConverterSMission("Pion ABC ArmerPointDeControle", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC ArmerPointDeControle"), eSMission_Pion_ABC_ArmerPointDeControle ),
    T_ConverterSMission("Pion ABC OrganiserAccueilColonneRefugies", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC OrganiserAccueilColonneRefugies"), eSMission_Pion_ABC_OrganiserAccueilColonneRefugies ),
    T_ConverterSMission("Pion ABC AppuyerSurPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC AppuyerSurPosition"), eSMission_Pion_ABC_AppuyerSurPosition ),
    T_ConverterSMission("Pion ABC RASIT RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ABC RASIT RenseignerSur"), eSMission_Pion_ABC_RASIT_RenseignerSur ),
    T_ConverterSMission("Pion GEN RealiserFosseAC", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserFosseAC"), eSMission_Pion_GEN_RealiserFosseAC ),
    T_ConverterSMission("Pion GEN RealiserAbattisMine", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserAbattisMine"), eSMission_Pion_GEN_RealiserAbattisMine ),
    T_ConverterSMission("Pion GEN RealiserPointMine", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserPointMine"), eSMission_Pion_GEN_RealiserPointMine ),
    T_ConverterSMission("Pion GEN RealiserBarricade", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserBarricade"), eSMission_Pion_GEN_RealiserBarricade ),
    T_ConverterSMission("Pion GEN RealiserEboulement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserEboulement"), eSMission_Pion_GEN_RealiserEboulement ),
    T_ConverterSMission("Pion GEN RealiserBouchonMine", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserBouchonMine"), eSMission_Pion_GEN_RealiserBouchonMine ),
    T_ConverterSMission("Pion GEN DetruireRoute", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DetruireRoute"), eSMission_Pion_GEN_DetruireRoute ),
    T_ConverterSMission("Pion GEN DetruirePont", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DetruirePont"), eSMission_Pion_GEN_DetruirePont ),
    T_ConverterSMission("Pion GEN SecuriserItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN SecuriserItineraire"), eSMission_Pion_GEN_SecuriserItineraire ),
    T_ConverterSMission("Pion GEN DegagerAbattisMine", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DegagerAbattisMine"), eSMission_Pion_GEN_DegagerAbattisMine ),
    T_ConverterSMission("Pion GEN DegagerEboulement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DegagerEboulement"), eSMission_Pion_GEN_DegagerEboulement ),
    T_ConverterSMission("Pion GEN DegagerRues", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DegagerRues"), eSMission_Pion_GEN_DegagerRues ),
    T_ConverterSMission("Pion GEN ComblerEntonnoir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ComblerEntonnoir"), eSMission_Pion_GEN_ComblerEntonnoir ),
    T_ConverterSMission("Pion GEN ComblerFosseAC", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ComblerFosseAC"), eSMission_Pion_GEN_ComblerFosseAC ),
    T_ConverterSMission("Pion GEN CreerContournement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN CreerContournement"), eSMission_Pion_GEN_CreerContournement ),
    T_ConverterSMission("Pion GEN RealiserZoneMineeLineaire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserZoneMineeLineaire"), eSMission_Pion_GEN_RealiserZoneMineeLineaire ),
    T_ConverterSMission("Pion GEN OuvrirTrouee", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN OuvrirTrouee"), eSMission_Pion_GEN_OuvrirTrouee ),
    T_ConverterSMission("Pion GEN Renforcer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN Renforcer"), eSMission_Pion_GEN_Renforcer ),
    T_ConverterSMission("Pion GEN FranchirEntonnoir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN FranchirEntonnoir"), eSMission_Pion_GEN_FranchirEntonnoir ),
    T_ConverterSMission("Pion GEN FranchirFosseAC", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN FranchirFosseAC"), eSMission_Pion_GEN_FranchirFosseAC ),
    T_ConverterSMission("Pion GEN RealiserZoneMineeParDispersion", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserZoneMineeParDispersion"), eSMission_Pion_GEN_RealiserZoneMineeParDispersion ),
    T_ConverterSMission("Pion GEN RealiserPostesTir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserPostesTir"), eSMission_Pion_GEN_RealiserPostesTir ),
    T_ConverterSMission("Pion GEN RealiserTravauxProtection", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserTravauxProtection"), eSMission_Pion_GEN_RealiserTravauxProtection ),
    T_ConverterSMission("Pion GEN RetablirItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RetablirItineraire"), eSMission_Pion_GEN_RetablirItineraire ),
    T_ConverterSMission("Pion GEN EquiperExploiter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN EquiperExploiter"), eSMission_Pion_GEN_EquiperExploiter ),
    T_ConverterSMission("Pion GEN ExecuterVariantement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ExecuterVariantement"), eSMission_Pion_GEN_ExecuterVariantement ),
    T_ConverterSMission("Pion GEN ReconnaitreSiteFranchissement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ReconnaitreSiteFranchissement"), eSMission_Pion_GEN_ReconnaitreSiteFranchissement ),
    T_ConverterSMission("Pion GEN ReconnaitreItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ReconnaitreItineraire"), eSMission_Pion_GEN_ReconnaitreItineraire ),
    T_ConverterSMission("Pion GEN DeminerSiteFranchissement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DeminerSiteFranchissement"), eSMission_Pion_GEN_DeminerSiteFranchissement ),
    T_ConverterSMission("Pion GEN ReconnaitreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ReconnaitreZone"), eSMission_Pion_GEN_ReconnaitreZone ),
    T_ConverterSMission("Pion GEN CreerPlateForme", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN CreerPlateForme"), eSMission_Pion_GEN_CreerPlateForme ),
    T_ConverterSMission("Pion GEN CreerPiste", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN CreerPiste"), eSMission_Pion_GEN_CreerPiste ),
    T_ConverterSMission("Pion GEN CreerAirePoser", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN CreerAirePoser"), eSMission_Pion_GEN_CreerAirePoser ),
    T_ConverterSMission("Pion GEN NeutraliserEnginsExplosifs", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN NeutraliserEnginsExplosifs"), eSMission_Pion_GEN_NeutraliserEnginsExplosifs ),
    T_ConverterSMission("Pion GEN ActiverObstacle", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ActiverObstacle"), eSMission_Pion_GEN_ActiverObstacle ),
    T_ConverterSMission("Pion GEN AmeliorerMobilite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN AmeliorerMobilite"), eSMission_Pion_GEN_AmeliorerMobilite ),
    T_ConverterSMission("Pion GEN RealiserAireLogistique", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserAireLogistique"), eSMission_Pion_GEN_RealiserAireLogistique ),
    T_ConverterSMission("Pion GEN DepolluerZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN DepolluerZone"), eSMission_Pion_GEN_DepolluerZone ),
    T_ConverterSMission("Pion GEN AmenagerTerrainPoser", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN AmenagerTerrainPoser"), eSMission_Pion_GEN_AmenagerTerrainPoser ),
    T_ConverterSMission("Pion GEN RealiserPlateFormeDeploiement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserPlateFormeDeploiement"), eSMission_Pion_GEN_RealiserPlateFormeDeploiement ),
    T_ConverterSMission("Pion GEN ReprendreMissionConstruction", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN ReprendreMissionConstruction"), eSMission_Pion_GEN_ReprendreMissionConstruction ),
    T_ConverterSMission("Pion GEN RealiserZonePoserHelicoptere", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserZonePoserHelicoptere"), eSMission_Pion_GEN_RealiserZonePoserHelicoptere ),
    T_ConverterSMission("Pion GEN AppuyerDebarquementTroupesGU", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN AppuyerDebarquementTroupesGU"), eSMission_Pion_GEN_AppuyerDebarquementTroupesGU ),
    T_ConverterSMission("Pion GEN RealiserCampPrisonniers", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserCampPrisonniers"), eSMission_Pion_GEN_RealiserCampPrisonniers ),
    T_ConverterSMission("Pion GEN RealiserCampRefugies", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion GEN RealiserCampRefugies"), eSMission_Pion_GEN_RealiserCampRefugies ),
    T_ConverterSMission("Pion INF ReconnaitreAxe", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF ReconnaitreAxe"), eSMission_Pion_INF_ReconnaitreAxe ),
    T_ConverterSMission("Pion INF Couvrir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Couvrir"), eSMission_Pion_INF_Couvrir ),
    T_ConverterSMission("Pion INF Reduire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Reduire"), eSMission_Pion_INF_Reduire ),
    T_ConverterSMission("Pion INF Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Appuyer"), eSMission_Pion_INF_Appuyer ),
    T_ConverterSMission("Pion INF Fixer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Fixer"), eSMission_Pion_INF_Fixer ),
    T_ConverterSMission("Pion INF ControlerSecteur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF ControlerSecteur"), eSMission_Pion_INF_ControlerSecteur ),
    T_ConverterSMission("Pion INF SurveillerSecteur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF SurveillerSecteur"), eSMission_Pion_INF_SurveillerSecteur ),
    T_ConverterSMission("Pion INF Barrer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Barrer"), eSMission_Pion_INF_Barrer ),
    T_ConverterSMission("Pion INF ReconnaitrePoint", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF ReconnaitrePoint"), eSMission_Pion_INF_ReconnaitrePoint ),
    T_ConverterSMission("Pion INF Eclairer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Eclairer"), eSMission_Pion_INF_Eclairer ),
    T_ConverterSMission("Pion INF Interdire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Interdire"), eSMission_Pion_INF_Interdire ),
    T_ConverterSMission("Pion INF Semparer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Semparer"), eSMission_Pion_INF_Semparer ),
    T_ConverterSMission("Pion INF PrendrePreciserContact", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF PrendrePreciserContact"), eSMission_Pion_INF_PrendrePreciserContact ),
    T_ConverterSMission("Pion INF Defendre", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Defendre"), eSMission_Pion_INF_Defendre ),
    T_ConverterSMission("Pion INF DetruireEmbuscade", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF DetruireEmbuscade"), eSMission_Pion_INF_DetruireEmbuscade ),
    T_ConverterSMission("Pion INF ContreAttaquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF ContreAttaquer"), eSMission_Pion_INF_ContreAttaquer ),
    T_ConverterSMission("Pion INF Freiner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Freiner"), eSMission_Pion_INF_Freiner ),
    T_ConverterSMission("Pion INF FlancGarder", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF FlancGarder"), eSMission_Pion_INF_FlancGarder ),
    T_ConverterSMission("Pion INF OrganiserUnCheckPoint", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF OrganiserUnCheckPoint"), eSMission_Pion_INF_OrganiserUnCheckPoint ),
    T_ConverterSMission("Pion INF Harceler", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Harceler"), eSMission_Pion_INF_Harceler ),
    T_ConverterSMission("Pion INF DetruireParCoupDeMain", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF DetruireParCoupDeMain"), eSMission_Pion_INF_DetruireParCoupDeMain ),
    T_ConverterSMission("Pion INF EscorterUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF EscorterUnite"), eSMission_Pion_INF_EscorterUnite ),
    T_ConverterSMission("Pion INF EscorterUnites", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF EscorterUnites"), eSMission_Pion_INF_EscorterUnites ),
    T_ConverterSMission("Pion INF RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF RenseignerSur"), eSMission_Pion_INF_RenseignerSur ),
    T_ConverterSMission("Pion INF Soutenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Soutenir"), eSMission_Pion_INF_Soutenir ),
    T_ConverterSMission("Pion INF Securiser", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Securiser"), eSMission_Pion_INF_Securiser ),
    T_ConverterSMission("Pion INF Recueillir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF Recueillir"), eSMission_Pion_INF_Recueillir ),
    T_ConverterSMission("Pion INF RepondreAAggression", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF RepondreAAggression"), eSMission_Pion_INF_RepondreAAggression ),
    T_ConverterSMission("Pion INF AppuyerSurPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion INF AppuyerSurPosition"), eSMission_Pion_INF_AppuyerSurPosition ),
    T_ConverterSMission("Pion LOG SeDeployer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG SeDeployer"), eSMission_Pion_LOG_SeDeployer ),
    T_ConverterSMission("Pion LOG DistribuerMoyens", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG DistribuerMoyens"), eSMission_Pion_LOG_DistribuerMoyens ),
    T_ConverterSMission("Pion LOG TrierBlesses", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG TrierBlesses"), eSMission_Pion_LOG_TrierBlesses ),
    T_ConverterSMission("Pion LOG TraiterBlesses", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG TraiterBlesses"), eSMission_Pion_LOG_TraiterBlesses ),
    T_ConverterSMission("Pion LOG TrierEtTraiterBlesses", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG TrierEtTraiterBlesses"), eSMission_Pion_LOG_TrierEtTraiterBlesses ),
    T_ConverterSMission("Pion LOG SoignerBlesses", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG SoignerBlesses"), eSMission_Pion_LOG_SoignerBlesses ),
    T_ConverterSMission("Pion LOG PrendreEnCompteReactionsMentales", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG PrendreEnCompteReactionsMentales"), eSMission_Pion_LOG_PrendreEnCompteReactionsMentales ),
    T_ConverterSMission("Pion LOG DecontaminerBlesses", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG DecontaminerBlesses"), eSMission_Pion_LOG_DecontaminerBlesses ),
    T_ConverterSMission("Pion LOG Reparer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG Reparer"), eSMission_Pion_LOG_Reparer ),
    T_ConverterSMission("Pion LOG Evacuer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG Evacuer"), eSMission_Pion_LOG_Evacuer ),
    T_ConverterSMission("Pion LOG Convoyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG Convoyer"), eSMission_Pion_LOG_Convoyer ),
    T_ConverterSMission("Pion LOG DistribuerRessources", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG DistribuerRessources"), eSMission_Pion_LOG_DistribuerRessources ),
    T_ConverterSMission("Pion LOG ConstituerConvoi", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG ConstituerConvoi"), eSMission_Pion_LOG_ConstituerConvoi ),
    T_ConverterSMission("Pion LOG Livrer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG Livrer"), eSMission_Pion_LOG_Livrer ),
    T_ConverterSMission("Pion LOG PreparerBascule", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG PreparerBascule"), eSMission_Pion_LOG_PreparerBascule ),
    T_ConverterSMission("Pion LOG AppuyerMouvement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG AppuyerMouvement"), eSMission_Pion_LOG_AppuyerMouvement ),
    T_ConverterSMission("Pion LOG ReconnaitreItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG ReconnaitreItineraire"), eSMission_Pion_LOG_ReconnaitreItineraire ),
    T_ConverterSMission("Pion LOG TransporterUnite", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG TransporterUnite"), eSMission_Pion_LOG_TransporterUnite ),
    T_ConverterSMission("Pion LOG ReconnaitreZoneContaminee", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG ReconnaitreZoneContaminee"), eSMission_Pion_LOG_ReconnaitreZoneContaminee ),
    T_ConverterSMission("Pion LOG AppuyerMouvementDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG AppuyerMouvementDansZone"), eSMission_Pion_LOG_AppuyerMouvementDansZone ),
    T_ConverterSMission("Pion LOG MettreEnOeuvreZoneStationnement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG MettreEnOeuvreZoneStationnement"), eSMission_Pion_LOG_MettreEnOeuvreZoneStationnement ),
    T_ConverterSMission("Pion LOG AppuyerFranchissementSurUnPoint", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG AppuyerFranchissementSurUnPoint"), eSMission_Pion_LOG_AppuyerFranchissementSurUnPoint ),
    T_ConverterSMission("Pion LOG BloquerZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG BloquerZone"), eSMission_Pion_LOG_BloquerZone ),
    T_ConverterSMission("Pion LOG ReconnaitreZoneDeDeploiement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG ReconnaitreZoneDeDeploiement"), eSMission_Pion_LOG_ReconnaitreZoneDeDeploiement ),
    T_ConverterSMission("Pion LOG ArmerPIA", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG ArmerPIA"), eSMission_Pion_LOG_ArmerPIA ),
    T_ConverterSMission("Pion LOG Surveiller", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion LOG Surveiller"), eSMission_Pion_LOG_Surveiller ),
    T_ConverterSMission("Pion Test Heliporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test Heliporter"), eSMission_Pion_Test_Heliporter ),
    T_ConverterSMission("Pion Test MoveTo", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test MoveTo"), eSMission_Pion_Test_MoveTo ),
    T_ConverterSMission("Pion Test CreateObject", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test CreateObject"), eSMission_Pion_Test_CreateObject ),
    T_ConverterSMission("Pion Test DestroyObject", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test DestroyObject"), eSMission_Pion_Test_DestroyObject ),
    T_ConverterSMission("Pion Test CreateBypass", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test CreateBypass"), eSMission_Pion_Test_CreateBypass ),
    T_ConverterSMission("Pion Test Fire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test Fire"), eSMission_Pion_Test_Fire ),
    T_ConverterSMission("Pion Test ChangePosture", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test ChangePosture"), eSMission_Pion_Test_ChangePosture ),
    T_ConverterSMission("Pion Test PathFind", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test PathFind"), eSMission_Pion_Test_PathFind ),
    T_ConverterSMission("Pion Test FindPosition", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test FindPosition"), eSMission_Pion_Test_FindPosition ),
    T_ConverterSMission("Pion Test Reinforce", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Test Reinforce"), eSMission_Pion_Test_Reinforce ),
    T_ConverterSMission("Pion PlastronEnnemi", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion PlastronEnnemi"), eSMission_Pion_PlastronEnnemi ),
    T_ConverterSMission("Pion FaireMouvement", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion FaireMouvement"), eSMission_Pion_FaireMouvement ),
    T_ConverterSMission("Pion Suivre", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Suivre"), eSMission_Pion_Suivre ),
    T_ConverterSMission("Pion SeFaireDecontaminer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion SeFaireDecontaminer"), eSMission_Pion_SeFaireDecontaminer ),
    T_ConverterSMission("Pion Franchir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Franchir"), eSMission_Pion_Franchir ),
    T_ConverterSMission("Pion Decrocher", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Decrocher"), eSMission_Pion_Decrocher ),
    T_ConverterSMission("Pion Stationner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Stationner"), eSMission_Pion_Stationner ),
    T_ConverterSMission("Pion SeFaireTransporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion SeFaireTransporter"), eSMission_Pion_SeFaireTransporter ),
    T_ConverterSMission("Pion InterdireFranchissementPopulation", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion InterdireFranchissementPopulation"), eSMission_Pion_InterdireFranchissementPopulation ),
    T_ConverterSMission("Pion FilterPopulation", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion FilterPopulation"), eSMission_Pion_FilterPopulation ),
    T_ConverterSMission("Pion RenseignerSurPopulation", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RenseignerSurPopulation"), eSMission_Pion_RenseignerSurPopulation ),
    T_ConverterSMission("Pion CanaliserPopulation", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion CanaliserPopulation"), eSMission_Pion_CanaliserPopulation ),
    T_ConverterSMission("Pion SecuriserPopulationDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion SecuriserPopulationDansZone"), eSMission_Pion_SecuriserPopulationDansZone ),
    T_ConverterSMission("Pion SecuriserZoneContreMenacesAsymetriques", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion SecuriserZoneContreMenacesAsymetriques"), eSMission_Pion_SecuriserZoneContreMenacesAsymetriques ),
    T_ConverterSMission("Pion Generique", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion Generique"), eSMission_Pion_Generique ),
    T_ConverterSMission("Pion MILICE Provoquer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion MILICE Provoquer"), eSMission_Pion_MILICE_Provoquer ),
    T_ConverterSMission("Pion MILICE PrendreEtTenir", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion MILICE PrendreEtTenir"), eSMission_Pion_MILICE_PrendreEtTenir ),
    T_ConverterSMission("Pion MILICE DetruireEmbuscade", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion MILICE DetruireEmbuscade"), eSMission_Pion_MILICE_DetruireEmbuscade ),
    T_ConverterSMission("Pion JOINT MARINE Transporter", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion JOINT MARINE Transporter"), eSMission_Pion_JOINT_MARINE_Transporter ),
    T_ConverterSMission("Pion JOINT AIR EffectuerRaid", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion JOINT AIR EffectuerRaid"), eSMission_Pion_JOINT_AIR_EffectuerRaid ),
    T_ConverterSMission("Pion ASY SInfiltrer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASY SInfiltrer"), eSMission_Pion_ASY_SInfiltrer ),
    T_ConverterSMission("Pion ASY CommettreAttentatContrePopulation", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASY CommettreAttentatContrePopulation"), eSMission_Pion_ASY_CommettreAttentatContrePopulation ),
    T_ConverterSMission("Pion ASY CommettreAttentatContreForcesArmees", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASY CommettreAttentatContreForcesArmees"), eSMission_Pion_ASY_CommettreAttentatContreForcesArmees ),
    T_ConverterSMission("Pion ASY CommettreAttentatContreInstallation", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASY CommettreAttentatContreInstallation"), eSMission_Pion_ASY_CommettreAttentatContreInstallation ),
    T_ConverterSMission("Pion ASY CommettreExactionsSurPopulationDansZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASY CommettreExactionsSurPopulationDansZone"), eSMission_Pion_ASY_CommettreExactionsSurPopulationDansZone ),
    T_ConverterSMission("Pion ASY Renseigner", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion ASY Renseigner"), eSMission_Pion_ASY_Renseigner ),
    T_ConverterSMission("Pion NBC AnimerUnPlotDeDecontamination", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion NBC AnimerUnPlotDeDecontamination"), eSMission_Pion_NBC_AnimerUnPlotDeDecontamination ),
    T_ConverterSMission("Pion NBC ReconnaitreItineraire", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion NBC ReconnaitreItineraire"), eSMission_Pion_NBC_ReconnaitreItineraire ),
    T_ConverterSMission("Pion NBC ReconnaitreZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion NBC ReconnaitreZone"), eSMission_Pion_NBC_ReconnaitreZone ),
    T_ConverterSMission("Pion NBC DecontaminerZone", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion NBC DecontaminerZone"), eSMission_Pion_NBC_DecontaminerZone ),
    T_ConverterSMission("Pion NBC ReconnaitreUnSiteROTA", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion NBC ReconnaitreUnSiteROTA"), eSMission_Pion_NBC_ReconnaitreUnSiteROTA ),
    T_ConverterSMission("Pion RENS ROHUM RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROHUM RenseignerSur"), eSMission_Pion_RENS_ROHUM_RenseignerSur ),
    T_ConverterSMission("Pion RENS ROHUM SExfiltrer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROHUM SExfiltrer"), eSMission_Pion_RENS_ROHUM_SExfiltrer ),
    T_ConverterSMission("Pion RENS ROHUM OrienterGuider", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROHUM OrienterGuider"), eSMission_Pion_RENS_ROHUM_OrienterGuider ),
    T_ConverterSMission("Pion RENS ROEM Appuyer", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROEM Appuyer"), eSMission_Pion_RENS_ROEM_Appuyer ),
    T_ConverterSMission("Pion RENS ROEM RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROEM RenseignerSur"), eSMission_Pion_RENS_ROEM_RenseignerSur ),
    T_ConverterSMission("Pion RENS ROEM MettreEnOeuvre", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROEM MettreEnOeuvre"), eSMission_Pion_RENS_ROEM_MettreEnOeuvre ),
    T_ConverterSMission("Pion RENS RADINT RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS RADINT RenseignerSur"), eSMission_Pion_RENS_RADINT_RenseignerSur ),
    T_ConverterSMission("Pion RENS RADINT MettreEnOeuvre", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS RADINT MettreEnOeuvre"), eSMission_Pion_RENS_RADINT_MettreEnOeuvre ),
    T_ConverterSMission("Pion RENS ROIM MettreEnOeuvre", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROIM MettreEnOeuvre"), eSMission_Pion_RENS_ROIM_MettreEnOeuvre ),
    T_ConverterSMission("Pion RENS ROIM SDTI RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROIM SDTI RenseignerSur"), eSMission_Pion_RENS_ROIM_SDTI_RenseignerSur ),
    T_ConverterSMission("Pion RENS ROIM CL289 RenseignerSur", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion RENS ROIM CL289 RenseignerSur"), eSMission_Pion_RENS_ROIM_CL289_RenseignerSur ),
    T_ConverterSMission("Pion TRANS EtablirGererLiaison", QT_TRANSLATE_NOOP( "ADN_Enums", "Pion TRANS EtablirGererLiaison"), eSMission_Pion_TRANS_EtablirGererLiaison ),
    T_ConverterSMission("Population FaireMouvement", QT_TRANSLATE_NOOP( "ADN_Enums", "Population FaireMouvement"), eSMission_Population_FaireMouvement ),
    T_ConverterSMission("Population Manifester", QT_TRANSLATE_NOOP( "ADN_Enums", "Population Manifester"), eSMission_Population_Manifester ),
    T_ConverterSMission("Population CommettreExactions", QT_TRANSLATE_NOOP( "ADN_Enums", "Population CommettreExactions"), eSMission_Population_CommettreExactions ),

    T_ConverterSMission( ""           , ""                                           , (E_SMission)-1  )
};