<!DOCTYPE TS><TS>
<context>
    <name>ContentPage</name>
    <message>
        <source>Back</source>
        <translation>Retour</translation>
    </message>
</context>
<context>
    <name>HomePage</name>
    <message>
        <source>Self Training</source>
        <translation>Auto-entraînement</translation>
    </message>
    <message>
        <source>Multiplayer</source>
        <translation>Multi-joueur</translation>
    </message>
    <message>
        <source>Options</source>
        <translation>Options</translation>
    </message>
    <message>
        <source>Quit</source>
        <translation>Quitter</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>SWORD Officer Training</source>
        <translation>SWORD Officer Training</translation>
    </message>
</context>
<context>
    <name>QuitPage</name>
    <message>
        <source>Yes</source>
        <translation>Oui</translation>
    </message>
    <message>
        <source>No</source>
        <translation>Non</translation>
    </message>
</context>
<context>
    <name>ReplayPage</name>
    <message>
        <source>Replay</source>
        <translation>Rejeu</translation>
    </message>
</context>
<context>
    <name>ScenarioPage</name>
    <message>
        <source>Scenario</source>
        <translation>Scénario</translation>
    </message>
    <message>
        <source>Start</source>
        <translation>Démarrer</translation>
    </message>
</context>
<context>
    <name>SelfTrainingPage</name>
    <message>
        <source>Scenario</source>
        <translation>Scénario</translation>
    </message>
    <message>
        <source>Replay</source>
        <translation>Rejeu</translation>
    </message>
    <message>
        <source>Back</source>
        <translation>Retour</translation>
    </message>
</context>
</TS>
