// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2009 MASA Group
//
// *****************************************************************************

#ifndef __protocol_Protocol_h_
#define __protocol_Protocol_h_

// Here are the tag constants generated by MessageIdentifierFactory. The
// first element is the typeid name in VS2010, followed by the tag value.
//
// "class sword::AarToClient"            3335378374
// "class sword::AuthenticationToClient" 468259588
// "class sword::ClientToAar"            496354747
// "class sword::ClientToAuthentication" 3393095543
// "class sword::ClientToMessenger"      2651046712
// "class sword::ClientToReplay"         745507513
// "class sword::ClientToSim"            496449857
// "class sword::DispatcherToClient"     3012412245
// "class sword::DispatcherToSim"        4036107609
// "class sword::MessengerToClient"      4281023046
// "class sword::ReplayToClient"         2824568610
// "class sword::SimToClient"            3540368649

#pragma warning( push, 0 )
#include "protocol/proto/version.pb.h"
#include "protocol/proto/aar_client.pb.h"
#include "protocol/proto/authentication_client.pb.h"
#include "protocol/proto/client_aar.pb.h"
#include "protocol/proto/client_authentication.pb.h"
#include "protocol/proto/client_messenger.pb.h"
#include "protocol/proto/client_replay.pb.h"
#include "protocol/proto/client_simulation.pb.h"
#include "protocol/proto/dispatcher_client.pb.h"
#include "protocol/proto/dispatcher_simulation.pb.h"
#include "protocol/proto/messenger_client.pb.h"
#include "protocol/proto/replay_client.pb.h"
#include "protocol/proto/simulation_client.pb.h"
#pragma warning( pop )

#endif // __protocol_Protocol_h_
