/* This file was generated by ASN1C V5.31 on 02-Nov-2009 */

#include "Protocol.h"

void asn1Print_SimpleTest (ASN1ConstCharPtr name, ASN1T_SimpleTest* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.name", name);
   rtPrintCharStr (namebuf, pvalue->name);

}

void ASN1C_SimpleTest::Print (ASN1ConstCharPtr name)

{
   asn1Print_SimpleTest (name, &msgData);
}

void asn1Print__SeqOfSimpleTest (ASN1ConstCharPtr name, ASN1T__SeqOfSimpleTest* pvalue)
{
   char namebuf[512];

   printf ("%s.n = %d\n", name, pvalue->n);
   {
   ASN1UINT xx1;
   for (xx1 = 0; xx1 < pvalue->n; xx1++) {
      sprintf (namebuf, "%s.elem[%d]", name, xx1);
      asn1Print_SimpleTest (namebuf, &pvalue->elem[xx1]);
   }
   }

}

void ASN1C__SeqOfSimpleTest::Print (ASN1ConstCharPtr name)

{
   asn1Print__SeqOfSimpleTest (name, &msgData);
}

void asn1Print_CompositeStringTest (ASN1ConstCharPtr name, ASN1T_CompositeStringTest* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.test", name);
   asn1Print__SeqOfSimpleTest (namebuf, &pvalue->test);

}

void ASN1C_CompositeStringTest::Print (ASN1ConstCharPtr name)

{
   asn1Print_CompositeStringTest (name, &msgData);
}

void asn1Print_CompositeIntegerTest_test (ASN1ConstCharPtr name, ASN1T_CompositeIntegerTest_test* pvalue)
{
   char namebuf[512];

   printf ("%s.n = %d\n", name, pvalue->n);
   {
   ASN1UINT xx1;
   for (xx1 = 0; xx1 < pvalue->n; xx1++) {
      sprintf (namebuf, "%s.elem[%d]", name, xx1);
      rtPrintInteger (namebuf, pvalue->elem[xx1]);
   }
   }

}

void ASN1C_CompositeIntegerTest_test::Print (ASN1ConstCharPtr name)

{
   asn1Print_CompositeIntegerTest_test (name, &msgData);
}

void asn1Print_CompositeIntegerTest (ASN1ConstCharPtr name, ASN1T_CompositeIntegerTest* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.test", name);
   asn1Print_CompositeIntegerTest_test (namebuf, &pvalue->test);

}

void ASN1C_CompositeIntegerTest::Print (ASN1ConstCharPtr name)

{
   asn1Print_CompositeIntegerTest (name, &msgData);
}

