/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.31, Date: 02-Nov-2009.
 */
#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdio.h>
#include <stdlib.h>
#include "asn1per.h"
#include "asn1PerCppTypes.h"

/**************************************************************/
/*                                                            */
/*  SimpleTest                                                */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ASN1T_SimpleTest {
   ASN1VisibleString  name;
} ASN1T_SimpleTest;

class EXTERN ASN1C_SimpleTest : public ASN1CType {
public:
   ASN1T_SimpleTest& msgData;
   ASN1C_SimpleTest (
      ASN1MessageBuffer& msgBuf, ASN1T_SimpleTest& data);
   int Encode ();
   int Decode ();
   void Print (ASN1ConstCharPtr name);
} ;

EXTERN int asn1PE_SimpleTest (ASN1CTXT* ctxt_p, ASN1T_SimpleTest* pvalue);
EXTERN int asn1PD_SimpleTest (ASN1CTXT* ctxt_p, ASN1T_SimpleTest* pvalue);

EXTERN void asn1Print_SimpleTest (ASN1ConstCharPtr name, ASN1T_SimpleTest* pvalue);

/**************************************************************/
/*                                                            */
/*  _SeqOfSimpleTest                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ASN1T__SeqOfSimpleTest {
   ASN1UINT n;
   ASN1T_SimpleTest *elem;
} ASN1T__SeqOfSimpleTest;

class EXTERN ASN1C__SeqOfSimpleTest : public ASN1CType {
public:
   ASN1T__SeqOfSimpleTest& msgData;
   ASN1C__SeqOfSimpleTest (
      ASN1MessageBuffer& msgBuf, ASN1T__SeqOfSimpleTest& data);
   int Encode ();
   int Decode ();
   void Print (ASN1ConstCharPtr name);
} ;

EXTERN int asn1PE__SeqOfSimpleTest (ASN1CTXT* ctxt_p, ASN1T__SeqOfSimpleTest* pvalue);
EXTERN int asn1PD__SeqOfSimpleTest (ASN1CTXT* ctxt_p, ASN1T__SeqOfSimpleTest* pvalue);

EXTERN void asn1Print__SeqOfSimpleTest (ASN1ConstCharPtr name, ASN1T__SeqOfSimpleTest* pvalue);

/**************************************************************/
/*                                                            */
/*  CompositeStringTest                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ASN1T_CompositeStringTest {
   ASN1T__SeqOfSimpleTest  test;
} ASN1T_CompositeStringTest;

class EXTERN ASN1C_CompositeStringTest : public ASN1CType {
public:
   ASN1T_CompositeStringTest& msgData;
   ASN1C_CompositeStringTest (
      ASN1MessageBuffer& msgBuf, ASN1T_CompositeStringTest& data);
   int Encode ();
   int Decode ();
   void Print (ASN1ConstCharPtr name);
} ;

EXTERN int asn1PE_CompositeStringTest (ASN1CTXT* ctxt_p, ASN1T_CompositeStringTest* pvalue);
EXTERN int asn1PD_CompositeStringTest (ASN1CTXT* ctxt_p, ASN1T_CompositeStringTest* pvalue);

EXTERN void asn1Print_CompositeStringTest (ASN1ConstCharPtr name, ASN1T_CompositeStringTest* pvalue);

/**************************************************************/
/*                                                            */
/*  CompositeIntegerTest_test                                 */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ASN1T_CompositeIntegerTest_test {
   ASN1UINT n;
   ASN1INT  *elem;
} ASN1T_CompositeIntegerTest_test;

class EXTERN ASN1C_CompositeIntegerTest_test : public ASN1CType {
public:
   ASN1T_CompositeIntegerTest_test& msgData;
   ASN1C_CompositeIntegerTest_test (
      ASN1MessageBuffer& msgBuf, ASN1T_CompositeIntegerTest_test& data);
   int Encode ();
   int Decode ();
   void Print (ASN1ConstCharPtr name);
} ;

EXTERN int asn1PE_CompositeIntegerTest_test (ASN1CTXT* ctxt_p, ASN1T_CompositeIntegerTest_test* pvalue);
EXTERN int asn1PD_CompositeIntegerTest_test (ASN1CTXT* ctxt_p, ASN1T_CompositeIntegerTest_test* pvalue);

EXTERN void asn1Print_CompositeIntegerTest_test (ASN1ConstCharPtr name, ASN1T_CompositeIntegerTest_test* pvalue);

/**************************************************************/
/*                                                            */
/*  CompositeIntegerTest                                      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ASN1T_CompositeIntegerTest {
   ASN1T_CompositeIntegerTest_test  test;
} ASN1T_CompositeIntegerTest;

class EXTERN ASN1C_CompositeIntegerTest : public ASN1CType {
public:
   ASN1T_CompositeIntegerTest& msgData;
   ASN1C_CompositeIntegerTest (
      ASN1MessageBuffer& msgBuf, ASN1T_CompositeIntegerTest& data);
   int Encode ();
   int Decode ();
   void Print (ASN1ConstCharPtr name);
} ;

EXTERN int asn1PE_CompositeIntegerTest (ASN1CTXT* ctxt_p, ASN1T_CompositeIntegerTest* pvalue);
EXTERN int asn1PD_CompositeIntegerTest (ASN1CTXT* ctxt_p, ASN1T_CompositeIntegerTest* pvalue);

EXTERN void asn1Print_CompositeIntegerTest (ASN1ConstCharPtr name, ASN1T_CompositeIntegerTest* pvalue);

#endif
