/* soapH.h
   Generated by gSOAP 2.7.10 from DCSOperations.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__pullReport
#define SOAP_TYPE_ns1__pullReport (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pullReport(struct soap*, struct ns1__pullReport *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pullReport(struct soap*, const struct ns1__pullReport *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pullReport(struct soap*, const struct ns1__pullReport *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pullReport(struct soap*, const char*, int, const struct ns1__pullReport *, const char*);
SOAP_FMAC3 struct ns1__pullReport * SOAP_FMAC4 soap_get_ns1__pullReport(struct soap*, struct ns1__pullReport *, const char*, const char*);
SOAP_FMAC3 struct ns1__pullReport * SOAP_FMAC4 soap_in_ns1__pullReport(struct soap*, const char*, struct ns1__pullReport *, const char*);
SOAP_FMAC5 struct ns1__pullReport * SOAP_FMAC6 soap_new_ns1__pullReport(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pullReport(struct soap*, struct ns1__pullReport*);
SOAP_FMAC3 struct ns1__pullReport * SOAP_FMAC4 soap_instantiate_ns1__pullReport(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pullReport(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pullReportResponse
#define SOAP_TYPE_ns1__pullReportResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pullReportResponse(struct soap*, struct ns1__pullReportResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pullReportResponse(struct soap*, const struct ns1__pullReportResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pullReportResponse(struct soap*, const struct ns1__pullReportResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pullReportResponse(struct soap*, const char*, int, const struct ns1__pullReportResponse *, const char*);
SOAP_FMAC3 struct ns1__pullReportResponse * SOAP_FMAC4 soap_get_ns1__pullReportResponse(struct soap*, struct ns1__pullReportResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__pullReportResponse * SOAP_FMAC4 soap_in_ns1__pullReportResponse(struct soap*, const char*, struct ns1__pullReportResponse *, const char*);
SOAP_FMAC5 struct ns1__pullReportResponse * SOAP_FMAC6 soap_new_ns1__pullReportResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pullReportResponse(struct soap*, struct ns1__pullReportResponse*);
SOAP_FMAC3 struct ns1__pullReportResponse * SOAP_FMAC4 soap_instantiate_ns1__pullReportResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pullReportResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pullOrder
#define SOAP_TYPE_ns1__pullOrder (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pullOrder(struct soap*, struct ns1__pullOrder *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pullOrder(struct soap*, const struct ns1__pullOrder *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pullOrder(struct soap*, const struct ns1__pullOrder *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pullOrder(struct soap*, const char*, int, const struct ns1__pullOrder *, const char*);
SOAP_FMAC3 struct ns1__pullOrder * SOAP_FMAC4 soap_get_ns1__pullOrder(struct soap*, struct ns1__pullOrder *, const char*, const char*);
SOAP_FMAC3 struct ns1__pullOrder * SOAP_FMAC4 soap_in_ns1__pullOrder(struct soap*, const char*, struct ns1__pullOrder *, const char*);
SOAP_FMAC5 struct ns1__pullOrder * SOAP_FMAC6 soap_new_ns1__pullOrder(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pullOrder(struct soap*, struct ns1__pullOrder*);
SOAP_FMAC3 struct ns1__pullOrder * SOAP_FMAC4 soap_instantiate_ns1__pullOrder(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pullOrder(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pullOrderResponse
#define SOAP_TYPE_ns1__pullOrderResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pullOrderResponse(struct soap*, struct ns1__pullOrderResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pullOrderResponse(struct soap*, const struct ns1__pullOrderResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pullOrderResponse(struct soap*, const struct ns1__pullOrderResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pullOrderResponse(struct soap*, const char*, int, const struct ns1__pullOrderResponse *, const char*);
SOAP_FMAC3 struct ns1__pullOrderResponse * SOAP_FMAC4 soap_get_ns1__pullOrderResponse(struct soap*, struct ns1__pullOrderResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__pullOrderResponse * SOAP_FMAC4 soap_in_ns1__pullOrderResponse(struct soap*, const char*, struct ns1__pullOrderResponse *, const char*);
SOAP_FMAC5 struct ns1__pullOrderResponse * SOAP_FMAC6 soap_new_ns1__pullOrderResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pullOrderResponse(struct soap*, struct ns1__pullOrderResponse*);
SOAP_FMAC3 struct ns1__pullOrderResponse * SOAP_FMAC4 soap_instantiate_ns1__pullOrderResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pullOrderResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pushReport
#define SOAP_TYPE_ns1__pushReport (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pushReport(struct soap*, struct ns1__pushReport *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pushReport(struct soap*, const struct ns1__pushReport *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pushReport(struct soap*, const struct ns1__pushReport *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pushReport(struct soap*, const char*, int, const struct ns1__pushReport *, const char*);
SOAP_FMAC3 struct ns1__pushReport * SOAP_FMAC4 soap_get_ns1__pushReport(struct soap*, struct ns1__pushReport *, const char*, const char*);
SOAP_FMAC3 struct ns1__pushReport * SOAP_FMAC4 soap_in_ns1__pushReport(struct soap*, const char*, struct ns1__pushReport *, const char*);
SOAP_FMAC5 struct ns1__pushReport * SOAP_FMAC6 soap_new_ns1__pushReport(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pushReport(struct soap*, struct ns1__pushReport*);
SOAP_FMAC3 struct ns1__pushReport * SOAP_FMAC4 soap_instantiate_ns1__pushReport(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pushReport(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pushReportResponse
#define SOAP_TYPE_ns1__pushReportResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pushReportResponse(struct soap*, struct ns1__pushReportResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pushReportResponse(struct soap*, const struct ns1__pushReportResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pushReportResponse(struct soap*, const struct ns1__pushReportResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pushReportResponse(struct soap*, const char*, int, const struct ns1__pushReportResponse *, const char*);
SOAP_FMAC3 struct ns1__pushReportResponse * SOAP_FMAC4 soap_get_ns1__pushReportResponse(struct soap*, struct ns1__pushReportResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__pushReportResponse * SOAP_FMAC4 soap_in_ns1__pushReportResponse(struct soap*, const char*, struct ns1__pushReportResponse *, const char*);
SOAP_FMAC5 struct ns1__pushReportResponse * SOAP_FMAC6 soap_new_ns1__pushReportResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pushReportResponse(struct soap*, struct ns1__pushReportResponse*);
SOAP_FMAC3 struct ns1__pushReportResponse * SOAP_FMAC4 soap_instantiate_ns1__pushReportResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pushReportResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pushOrder
#define SOAP_TYPE_ns1__pushOrder (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pushOrder(struct soap*, struct ns1__pushOrder *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pushOrder(struct soap*, const struct ns1__pushOrder *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pushOrder(struct soap*, const struct ns1__pushOrder *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pushOrder(struct soap*, const char*, int, const struct ns1__pushOrder *, const char*);
SOAP_FMAC3 struct ns1__pushOrder * SOAP_FMAC4 soap_get_ns1__pushOrder(struct soap*, struct ns1__pushOrder *, const char*, const char*);
SOAP_FMAC3 struct ns1__pushOrder * SOAP_FMAC4 soap_in_ns1__pushOrder(struct soap*, const char*, struct ns1__pushOrder *, const char*);
SOAP_FMAC5 struct ns1__pushOrder * SOAP_FMAC6 soap_new_ns1__pushOrder(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pushOrder(struct soap*, struct ns1__pushOrder*);
SOAP_FMAC3 struct ns1__pushOrder * SOAP_FMAC4 soap_instantiate_ns1__pushOrder(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pushOrder(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__pushOrderResponse
#define SOAP_TYPE_ns1__pushOrderResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__pushOrderResponse(struct soap*, struct ns1__pushOrderResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__pushOrderResponse(struct soap*, const struct ns1__pushOrderResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__pushOrderResponse(struct soap*, const struct ns1__pushOrderResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__pushOrderResponse(struct soap*, const char*, int, const struct ns1__pushOrderResponse *, const char*);
SOAP_FMAC3 struct ns1__pushOrderResponse * SOAP_FMAC4 soap_get_ns1__pushOrderResponse(struct soap*, struct ns1__pushOrderResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__pushOrderResponse * SOAP_FMAC4 soap_in_ns1__pushOrderResponse(struct soap*, const char*, struct ns1__pushOrderResponse *, const char*);
SOAP_FMAC5 struct ns1__pushOrderResponse * SOAP_FMAC6 soap_new_ns1__pushOrderResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__pushOrderResponse(struct soap*, struct ns1__pushOrderResponse*);
SOAP_FMAC3 struct ns1__pushOrderResponse * SOAP_FMAC4 soap_instantiate_ns1__pushOrderResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__pushOrderResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
