--
-- file name : Aar.asn
--
-- Messages de gestion des attributs d'une unité
--

Aar DEFINITIONS AUTOMATIC TAGS ::= BEGIN

-- BEGIN includes
IMPORTS BaseExports FROM Base;
AarIncludes ::= SEQUENCE { BaseExports }
AarExports  ::= NULL
-- END includes

MsgAarInformation ::= SEQUENCE
{
    information VisibleString -- $$$$ XmlOverAsn pattern
}

MsgIndicatorResult ::= SEQUENCE
{
    values SEQUENCE OF REAL
}

MsgIndicatorRequest ::= SEQUENCE
{
    request VisibleString -- $$$$ XmlOverAsn pattern again
}

END -- Aar
