--
-- file name : Fire.asn
--
-- Messages de gestion des tirs
--

Fire DEFINITIONS AUTOMATIC TAGS ::= BEGIN

-- BEGIN includes
IMPORTS BaseExports FROM Base;
FireIncludes ::= SEQUENCE { BaseExports }
FireExports  ::= NULL
-- END includes

UnitHumanFireDamage ::= SEQUENCE
{
    rang                        EnumHumanRank,
    nb-non-blesses              INTEGER, -- NB : toutes les valeurs peuvent être négatives
    nb-morts                    INTEGER,
    nb-blesses-urgence-1        INTEGER,
    nb-blesses-urgence-2        INTEGER,
    nb-blesses-urgence-3        INTEGER,
    nb-blesses-urgence-extreme  INTEGER
}

UnitEquipmentFireDamage ::= SEQUENCE
{
    type-equipement  EquipmentType,
    nb-disponibles   INTEGER,
    nb-indisponibles INTEGER,
    nb-reparables    INTEGER
}

UnitFireDamages ::= SEQUENCE
{
    cible       Unit,
    humains     SEQUENCE OF UnitHumanFireDamage,
    equipements SEQUENCE OF UnitEquipmentFireDamage
}

PopulationFireDamages ::= SEQUENCE
{
    cible       Population,
    nb-morts    INTEGER
}

UnitsFireDamages       ::= SEQUENCE OF UnitFireDamages
PopulationsFireDamages ::= SEQUENCE OF PopulationFireDamages

-- Tir pion
MsgStartUnitFire ::= SEQUENCE
{
    oid-tir     UnitFire,
    tireur      Unit,
    cible       CHOICE
    {
        pion       Unit,
        population Population,
        position   CoordUTM
    },
    type        ENUMERATED
    {
        direct,
        indirect
    },
    munition    DotationType OPTIONAL
}

MsgStopUnitFire ::= SEQUENCE
{
    oid-tir            UnitFire,
    degats-pions       UnitsFireDamages,
    degats-populations PopulationsFireDamages
}

-- Tir population
MsgStartPopulationFire ::= SEQUENCE
{
    oid-tir     PopulationFire,
    oid-src     Population
}

MsgStopPopulationFire ::= SEQUENCE
{
    oid-tir      PopulationFire,
    degats-pions UnitsFireDamages
}

-- Explosion mine
MsgExplosion ::= SEQUENCE
{
    oid-objet          OID,
    degats-pions       UnitsFireDamages,
    degats-populations PopulationsFireDamages
}

-- Effets de tirs
EnumFireEffectType ::= ENUMERATED
{
    fumigene    (0),
    eclairant   (1)
}

MsgStartFireEffect ::= SEQUENCE
{
    oid-effet       OID,
    localisation    Location,
    type            EnumFireEffectType
}

MsgStopFireEffect ::= OID


END -- Fire
