--
-- file name : Messages.asn
--
-- Liste des messages
--

Messages DEFINITIONS AUTOMATIC TAGS ::= BEGIN

-- BEGIN includes
IMPORTS BaseExports                   FROM Base
        LimaLimiteExports             FROM LimaLimite
        OrderExports                  FROM Order
        ControlExports                FROM Control
        KnowledgeGroupExports         FROM KnowledgeGroup
        FormationExports              FROM Formation
        FireExports                   FROM Fire
        UnitExports                   FROM Unit
        UnitKnowledgeExports          FROM UnitKnowledge
        ObjectExports                 FROM Object
        ObjectKnowledgeExports        FROM ObjectKnowledge
        PopulationExports             FROM Population
        PopulationKnowledgeExports    FROM PopulationKnowledge
        LogMaintenanceExports         FROM LogMaintenance
        LogRavitaillementExports      FROM LogRavitaillement
        LogSanteExports               FROM LogSante
        AutomateExports               FROM Automat
        ArmyExports                   FROM Army
        AuthExports                   FROM Auth;
MessagesIncludes ::= SEQUENCE
{ BaseExports, LimaLimiteExports, OrderExports, ControlExports, KnowledgeGroupExports, 
  FormationExports, FireExports, UnitExports, UnitKnowledgeExports, ObjectExports, 
  ObjectKnowledgeExports, PopulationExports, PopulationKnowledgeExports, LogMaintenanceExports,
  LogRavitaillementExports, LogSanteExports, AutomateExports, ArmyExports, AuthExports }
MessagesExports  ::= NULL
-- END includes


--
--
--
MsgsSimToClient ::= SEQUENCE
{
    context INTEGER DEFAULT 0,
    msg     CHOICE
    {
        -- ACKS
        msg-limit-creation-request-ack                          MsgLimitCreationRequestAck,
        msg-limit-destruction-request-ack                       MsgLimitDestructionRequestAck,
        msg-limit-update-request-ack                            MsgLimitUpdateRequestAck,
        msg-lima-creation-request-ack                           MsgLimaCreationRequestAck,
        msg-lima-destruction-request-ack                        MsgLimaDestructionRequestAck,
        msg-lima-update-request-ack                             MsgLimaUpdateRequestAck,

        msg-pion-order-ack                                      MsgUnitOrderAck,
        msg-automate-order-ack                                  MsgAutomatOrderAck,
        msg-population-order-ack                                MsgPopulationOrderAck,
        msg-frag-order-ack                                      MsgFragOrderAck,                                                                
        msg-set-automate-mode-ack                               MsgSetAutomatModeAck,
        msg-unit-creation-request-ack                           MsgUnitCreationRequestAck,
        msg-unit-magic-action-ack                               MsgUnitMagicActionAck,
        msg-object-magic-action-ack                             MsgObjectMagicActionAck,
        msg-population-magic-action-ack                         MsgPopulationMagicActionAck,

        msg-change-diplomatie-ack                               MsgChangeDiplomacyAck,
        msg-automate-change-groupe-connaissance-ack             MsgAutomatChangeKnowledgeGroupAck,
        msg-automate-change-liens-logistiques-ack               MsgAutomatChangeLogisticLinksAck,
        msg-pion-change-superior-ack                            MsgUnitChangeSuperiorAck,   

        msg-log-ravitaillement-pousser-flux-ack                 MsgLogSupplyPushFlowAck,
        msg-log-ravitaillement-change-quotas-ack                MsgLogSupplyChangeQuotasAck,   

        -- MESSAGES
        msg-ctrl-info                                           MsgControlInformation,
        msg-ctrl-begin-tick                                     MsgControlBeginTick,
        msg-ctrl-end-tick                                       MsgControlEndTick,
        msg-ctrl-stop-ack                                       MsgControlStopAck,
        msg-ctrl-pause-ack                                      MsgControlPauseAck,
        msg-ctrl-resume-ack                                     MsgControlResumeAck,
        msg-ctrl-change-time-factor-ack                         MsgControlChangeTimeFactorAck,
        msg-ctrl-meteo-globale-ack                              MsgControlGlobalMeteoAck,
        msg-ctrl-meteo-locale-ack                               MsgControlLocalMeteoAck,
        msg-ctrl-checkpoint-save-begin                          MsgControlCheckPointSaveBegin,
        msg-ctrl-checkpoint-save-end                            MsgControlCheckPointSaveEnd,
        msg-ctrl-checkpoint-set-frequency-ack                   MsgControlCheckPointSetFrequencyAck,
        msg-ctrl-checkpoint-save-now-ack                        MsgControlCheckPointSaveNowAck,
        msg-ctrl-send-current-state-begin                       MsgControlSendCurrentStateBegin,
        msg-ctrl-send-current-state-end                         MsgControlSendCurrentStateEnd,

        msg-limit-creation                                      MsgLimitCreation,
        msg-limit-update                                        MsgLimitUpdate,
        msg-limit-destruction                                   MsgLimitDestruction,
        msg-lima-creation                                       MsgLimaCreation,
        msg-lima-update                                         MsgLimaUpdate,
        msg-lima-destruction                                    MsgLimaDestruction, 

        msg-formation-creation                                  MsgFormationCreation,
        msg-knowledge-group-creation                            MsgKnowledgeGroupCreation,
        msg-side-creation                                       MsgTeamCreation,

        msg-automate-creation                                   MsgAutomatCreation,
        msg-automate-attributes                                 MsgAutomatAttributes,

        msg-pion-creation                                       MsgUnitCreation,
        msg-unit-attributes                                     MsgUnitAttributes,
        msg-unit-pathfind                                       MsgUnitPathFind,                
        msg-pion-destruction                                    MsgUnitDestruction,

        msg-change-diplomatie                                   MsgChangeDiplomacy,
        msg-pion-change-superior                                MsgUnitChangeSuperior,        
        msg-automate-change-liens-logistiques                   MsgAutomatChangeLogisticLinks,

        msg-unit-knowledge-creation                             MsgUnitKnowledgeCreation,
        msg-unit-knowledge-update                               MsgUnitKnowledgeUpdate,
        msg-unit-knowledge-destruction                          MsgUnitKnowledgeDestruction,

        msg-start-pion-fire                                     MsgStartUnitFire,
        msg-stop-pion-fire                                      MsgStopUnitFire,
        msg-start-population-fire                               MsgStartPopulationFire,
        msg-stop-population-fire                                MsgStopPopulationFire,        
        msg-explosion                                           MsgExplosion,
        msg-start-fire-effect                                   MsgStartFireEffect,
        msg-stop-fire-effect                                    MsgStopFireEffect,

        msg-cr                                                  MsgReport,
        msg-trace                                               MsgTrace,
        msg-decisional-state                                    MsgDecisionalState,

        msg-pion-order                                          MsgUnitOrder,        
        msg-automate-order                                      MsgAutomatOrder,
        msg-population-order                                    MsgPopulationOrder,

        msg-object-creation                                     MsgObjectCreation,
        msg-object-destruction                                  MsgObjectDestruction,
        msg-object-update                                       MsgObjectUpdate,
        msg-object-knowledge-creation                           MsgObjectKnowledgeCreation,
        msg-object-knowledge-update                             MsgObjectKnowledgeUpdate,
        msg-object-knowledge-destruction                        MsgObjectKnowledgeDestruction,

        msg-log-sante-traitement-humain-creation                MsgLogMedicalHandlingCreation,
        msg-log-sante-traitement-humain-update                  MsgLogMedicalHandlingUpdate,
        msg-log-sante-traitement-humain-destruction             MsgLogMedicalHandlingDestruction,
        msg-log-sante-etat                                      MsgLogMedicalState,

        msg-log-maintenance-traitement-equipement-creation      MsgLogMaintenanceHandlingCreation,
        msg-log-maintenance-traitement-equipement-update        MsgLogMaintenanceHandlingUpdate,
        msg-log-maintenance-traitement-equipement-destruction   MsgLogMaintenanceHandlingDestruction,
        msg-log-maintenance-etat                                MsgLogMaintenanceState,

        msg-log-ravitaillement-traitement-creation              MsgLogSupplyHandlingCreation,
        msg-log-ravitaillement-traitement-update                MsgLogSupplyHandlingUpdate,
        msg-log-ravitaillement-traitement-destruction           MsgLogSupplyHandlingDestruction,
        msg-log-ravitaillement-etat                             MsgLogSupplyState,
        msg-log-ravitaillement-quotas                           MsgLogSupplyQuotas,  

        msg-population-creation                                 MsgPopulationCreation,
        msg-population-update                                   MsgPopulationUpdate,
        msg-population-concentration-creation                   MsgPopulationConcentrationCreation,
        msg-population-concentration-destruction                MsgPopulationConcentrationDestruction,
        msg-population-concentration-update                     MsgPopulationConcentrationUpdate,
        msg-population-flux-creation                            MsgPopulationFlowCreation,
        msg-population-flux-destruction                         MsgPopulationFlowDestruction,
        msg-population-flux-update                              MsgPopulationFlowUpdate,

        msg-population-knowledge-creation                       MsgPopulationKnowledgeCreation,
        msg-population-knowledge-update                         MsgPopulationKnowledgeUpdate,
        msg-population-knowledge-destruction                    MsgPopulationKnowledgeDestruction,
        msg-population-concentration-knowledge-creation         MsgPopulationConcentrationKnowledgeCreation,
        msg-population-concentration-knowledge-destruction      MsgPopulationConcentrationKnowledgeDestruction,
        msg-population-concentration-knowledge-update           MsgPopulationConcentrationKnowledgeUpdate,
        msg-population-flux-knowledge-creation                  MsgPopulationFlowKnowledgeCreation,
        msg-population-flux-knowledge-destruction               MsgPopulationFlowKnowledgeDestruction,
        msg-population-flux-knowledge-update                    MsgPopulationFlowKnowledgeUpdate
    }    
}

MsgsClientToSim ::= SEQUENCE
{
    context INTEGER DEFAULT 0,
    msg     CHOICE
    {
        msg-ctrl-stop                           MsgControlStop,
        msg-ctrl-pause                          MsgControlPause,
        msg-ctrl-resume                         MsgControlResume,
        msg-ctrl-change-time-factor             MsgControlChangeTimeFactor,      
        msg-ctrl-meteo-globale                  MsgControlGlobalMeteo,
        msg-ctrl-meteo-locale                   MsgControlLocalMeteo,
        msg-ctrl-checkpoint-save-now            MsgControlCheckPointSaveNow,
        msg-ctrl-checkpoint-set-frequency       MsgControlCheckPointSetFrequency, 

        msg-limit-creation-request              MsgLimitCreationRequest,
        msg-limit-destruction-request           MsgLimitDestructionRequest,
        msg-limit-update-request                MsgLimitUpdateRequest,
        msg-lima-creation-request               MsgLimaCreationRequest,
        msg-lima-destruction-request            MsgLimaDestruction,
        msg-lima-update-request                 MsgLimaUpdateRequest,

        msg-pion-order                          MsgUnitOrder,
        msg-automate-order                      MsgAutomatOrder,
        msg-population-order                    MsgPopulationOrder,
        msg-frag-order                          MsgFragOrder,
       
        msg-set-automate-mode                   MsgSetAutomatMode,
        msg-unit-creation-request               MsgUnitCreationRequest,
        
        msg-unit-magic-action                   MsgUnitMagicAction,
        msg-object-magic-action                 MsgObjectMagicAction,
        msg-population-magic-action             MsgPopulationMagicAction,

        msg-change-diplomatie                   MsgChangeDiplomacy,
        msg-automate-change-groupe-connaissance MsgAutomatChangeKnowledgeGroup,
        msg-automate-change-liens-logistiques   MsgAutomatChangeLogisticLinks,
        msg-pion-change-superior                MsgUnitChangeSuperior,

        msg-log-ravitaillement-pousser-flux     MsgLogSupplyPushFlow,
        msg-log-ravitaillement-change-quotas    MsgLogSupplyChangeQuotas
    }
}

--
-- 
--  
MsgsSimToMiddle ::= SEQUENCE
{
    context INTEGER DEFAULT 0
--    msg     CHOICE
--    {
--    }    
}

MsgsMiddleToSim ::= SEQUENCE
{
    context INTEGER DEFAULT 0,
    msg     CHOICE
    {
        msg-ctrl-client-announcement MsgControlClientAnnouncement
    }
}

--
-- 
--  
MsgsMiddleToClient ::= SEQUENCE
{
    context INTEGER DEFAULT 0,
    msg     CHOICE
    {
        msg-ctrl-replay-info                MsgControlReplayInformation,
        msg-ctrl-skip-to-tick-ack           MsgControlSkipToTickAck,
        msg-authentication-response         MsgAuthenticationResponse,
        msg-profile-creation                MsgProfileCreation,
        msg-profile-creation-request-ack    MsgProfileCreationRequestAck,
        msg-profile-update                  MsgProfileUpdate,
        msg-profile-update-request-ack      MsgProfileUpdateRequestAck,
        msg-profile-destruction             MsgProfileDestruction,
        msg-profile-destruction-request-ack MsgProfileDestructionRequestAck
    }    
}

MsgsClientToMiddle ::= SEQUENCE
{
    context INTEGER DEFAULT 0,
    msg     CHOICE
    {       
        msg-ctrl-skip-to-tick           MsgControlSkipToTick,
        msg-authentication-request      MsgAuthenticationRequest,
        msg-profile-creation-request    MsgProfileCreationRequest,
        msg-profile-update-request      MsgProfileUpdateRequest,
        msg-profile-destruction-request MsgProfileDestructionRequest
    }
}

END
