--
-- file name : Object.asn
--
-- Messages de gestion des objets
--

ObjectKnowledge DEFINITIONS AUTOMATIC TAGS ::= BEGIN

-- BEGIN includes
IMPORTS BaseExports   FROM Base
        ObjectExports FROM Object;
ObjectKnowledgeIncludes ::= SEQUENCE { BaseExports, ObjectExports }
ObjectKnowledgeExports  ::= NULL
-- END includes

---------------------------
-- Connaissance objet
---------------------------

-- SIM -> MOS
MsgObjectKnowledgeCreation ::= SEQUENCE
{
    oid-connaissance             ObjectKnowledge, 
    oid-camp-possesseur          Team, 
    oid-objet-reel               OID, -- id de l'objet réel pointé par la connaissance
    type                         EnumObjectType,
    type-obstacle                EnumObstacleType   OPTIONAL,
    obstacle-de-manoeuvre-active BOOLEAN            OPTIONAL,    
    type-dotation-construction   DotationType       OPTIONAL,
    type-dotation-valorisation   DotationType       OPTIONAL    
}

MsgObjectKnowledgeUpdate ::= SEQUENCE
{
    oid-connaissance             ObjectKnowledge,
    oid-camp-possesseur          Team,
    oid-objet-reel               OID                OPTIONAL, -- id de l'objet réel pointé par la connaissance
    pertinence                   INTEGER( 0..100 )  OPTIONAL,
    localisation                 Location       OPTIONAL,
    pourcentage-construction     INTEGER( 0..100 )  OPTIONAL, 
    pourcentage-valorisation     INTEGER( 0..100 )  OPTIONAL,
    pourcentage-contournement    INTEGER( 0..100 )  OPTIONAL,
    obstacle-de-manoeuvre-active BOOLEAN            OPTIONAL,
    est-percu                    BOOLEAN            OPTIONAL,
    attributs-specifiques        ObjectAttributesSpecific OPTIONAL,
    perception-par-compagnie     ListOID            OPTIONAL, -- Liste des compagnies percevant l'objet
    nb-dotation-construction     INTEGER            OPTIONAL,
    nb-dotation-valorisation     INTEGER            OPTIONAL
}

MsgObjectKnowledgeDestruction ::= SEQUENCE
{
    oid-connaissance    ObjectKnowledge,    
    oid-camp-possesseur Team     
}

END -- ObjectKnowledge
