--
-- file name : Object.asn
--
-- Messages de gestion des objets
--

Object DEFINITIONS AUTOMATIC TAGS ::= BEGIN

-- BEGIN includes
IMPORTS BaseExports FROM Base;
ObjectIncludes ::= SEQUENCE { BaseExports }
ObjectExports  ::= NULL
-- END includes

EnumObstacleType ::= ENUMERATED
{
    initial(0),
    reserved(1)
}

EnumObjectType ::= ENUMERATED
{
    bouchon-mines               (0),
    zone-minee-lineaire         (1),
    zone-minee-par-dispersion   (2),
    fosse-anti-char             (3),
    abattis                     (4),
    barricade                   (5),
    eboulement                  (6),
    destruction-route           (7),
    destruction-pont            (8),
    pont-flottant-continu       (9), 
    poste-tir                   (10),
    zone-protegee               (11),
    zone-implantation-canon     (12),
    zone-implantation-cobra     (13),
    zone-implantation-lrm       (14),
    site-franchissement         (15),
    nuage-nbc                   (16), -- Doit etre une localisation de type 'cercle'
    plot-ravitaillement         (17),
    site-decontamination        (18),
    zone-brouillage-brod        (19),
    rota                        (20),
    zone-nbc                    (21), -- Doit etre une localisation de type 'cercle'
    zone-brouillage-bromure     (22),
    aire-poser                  (23),
    piste                       (24),
    plateforme                  (25),
    zone-mobilite-amelioree     (26),
    zone-poser-helicoptere      (27),
    aire-logistique             (28),
    itineraire-logistique       (29), -- Doit etre une localisation de type 'ligne'
    camp-prisonniers            (30),
    camp-refugies               (31),
    poste-controle              (32),
    terrain-largage             (33),
    zone-interdite-mouvement    (34),
    zone-interdite-tir          (35),
    zone-implantation-mortier   (36),
    pont-flottant-discontinu    (37),
    installation                (38),
    fire                        (39),
    emergency_shelter           (40)
}

EnumObjectErrorCode ::= ENUMERATED
{
    no-error                         (0),
    error-invalid-object             (1),
    error-invalid-id                 (2),
    error-invalid-camp               (3),
    error-invalid-localisation       (4),
    error-missing-specific-attributes(5),
    error-invalid-specific-attributes(6)
}


---------------------------
-- Attributs specifiques a certains objets
---------------------------     
ObjectAttributesCrossingSite ::= SEQUENCE
{
    width                 INTEGER,    -- en mètres
    depth                 INTEGER,    -- en mètres
    flow-rate             INTEGER,    -- en m/s
    banks-require-fitting BOOLEAN
}

ObjectAttributesNbcCloud ::= SEQUENCE
{
    nbc-agent OID -- Cf. Data/NBC.xml
}

ObjectAttributesNbcZone ::= SEQUENCE
{
    nbc-agent OID -- Cf. Data/NBC.xml
}

ObjectAttributesRota ::= SEQUENCE
{
    danger-level        INTEGER(0..10),
    nbc-agents          ListOID -- Cf. Data/NBC.xml
}

ObjectAttributesLogisticRoute ::= SEQUENCE
{
    equipped    BOOLEAN,
    max-weight  INTEGER,
    width       INTEGER,
    length      INTEGER,
    flow-rate   INTEGER
}

ObjectAttributesPrisonerCamp ::= SEQUENCE
{
    tc2  Automat
}

ObjectAttributesRefugeeCamp ::= SEQUENCE
{
    tc2  Automat
}

ObjectAttributesLinearMineArea ::= SEQUENCE
{
    density            REAL(0..5) DEFAULT 0,
    activity-time      INTEGER    DEFAULT 0       
}

ObjectAttributesDispersedMineArea ::= SEQUENCE
{
    density            REAL(0..5) DEFAULT 0,
    activity-time      INTEGER    DEFAULT 0       
}

ObjectAttributesMineJam ::= SEQUENCE
{
    activity-time INTEGER DEFAULT 0
}

ObjectAttributesSpecific ::= CHOICE
{
    crossing-site             ObjectAttributesCrossingSite,
    nbc-cloud                 ObjectAttributesNbcCloud,
    rota                      ObjectAttributesRota,
    nbc-zone                  ObjectAttributesNbcZone,
    logistic-route            ObjectAttributesLogisticRoute,
    prisoner-camp             ObjectAttributesPrisonerCamp,
    refugee-camp              ObjectAttributesRefugeeCamp,
    linear-mine-area          ObjectAttributesLinearMineArea,
    dispersed-mine-area       ObjectAttributesDispersedMineArea,
    mine-jam                  ObjectAttributesMineJam
}
 
---------------------------
-- Objet réel
---------------------------     

MsgObjectCreation ::= SEQUENCE
{
    oid                          OID,
    type                         EnumObjectType,
    obstacle-type                EnumObstacleType   OPTIONAL,
    reserved-obstacle-activated  BOOLEAN            OPTIONAL,    
    location                     Location,
    name                         VisibleString,
    team                         Team,
    specific-attributes          ObjectAttributesSpecific OPTIONAL,
    construction-dotation-type   DotationType       OPTIONAL,
    mining-dotation-type         DotationType       OPTIONAL
}

MsgObjectUpdate ::= SEQUENCE
{
    oid                                 OID,
    construction-percentage             INTEGER( 0..100 )  OPTIONAL, 
    mining-percentage                   INTEGER( 0..100 )  OPTIONAL,
    bypass-construction-percentage      INTEGER( 0..100 )  OPTIONAL,   
    reserved-obstacle-activated         BOOLEAN            OPTIONAL,
    construction-dotation-nbr           INTEGER            OPTIONAL,
    mining-dotation-nbr                 INTEGER            OPTIONAL,   
    location                            Location       OPTIONAL,
    specific-attributes                 ObjectAttributesSpecific OPTIONAL
}

MsgObjectDestruction ::= OID


---------------------------
-- Actions magiques
---------------------------

MagicActionUpdateObject ::= SEQUENCE
{
    oid                             OID,
    construction-percentage         INTEGER( 0..100 ) OPTIONAL, 
    mining-percentage               INTEGER( 0..100 ) OPTIONAL,
    bypass-construction-percentage  INTEGER( 0..100 ) OPTIONAL,
    reserved-obstacle-activated     BOOLEAN           OPTIONAL
}

MagicActionCreateObject ::= SEQUENCE
{
    team                         Team, 
    type                         EnumObjectType,
    obstacle-type                EnumObstacleType   OPTIONAL,
    reserved-obstacle-activated  BOOLEAN            OPTIONAL,
    location                     Location,
    name                         VisibleString      OPTIONAL,    
    specific-attributes          ObjectAttributesSpecific OPTIONAL
}

MagicActionDestroyObjet ::= OID -- oid-objet

MsgObjectMagicAction ::= SEQUENCE
{
    action CHOICE
    {
        create-object   MagicActionCreateObject,
        update-object   MagicActionUpdateObject,
        destroy-object  MagicActionDestroyObjet
    }       
}

MsgObjectMagicActionAck ::= SEQUENCE
{
    error-code  EnumObjectErrorCode
}

END -- Object
